In [1]:
import pandas as pd
import sqlite3

conn = sqlite3.connect(":memory:")
cur = conn.cursor()

def q(sql):
 return pd.read_sql_query(sql, conn)


cur.executescript("""
DROP TABLE IF EXISTS customers;
DROP TABLE IF EXISTS orders;
DROP TABLE IF EXISTS payments;

CREATE TABLE customers (
 customer_id INTEGER PRIMARY KEY,
 customer_name TEXT,
 city TEXT,
 email TEXT,
 segment TEXT
);

CREATE TABLE orders (
 order_id INTEGER PRIMARY KEY,
 customer_id INTEGER,
 order_date TEXT,
 amount REAL,
 status TEXT,
 coupon_code TEXT
);

CREATE TABLE payments (
 payment_id INTEGER PRIMARY KEY,
 order_id INTEGER,
 payment_status TEXT,
 payment_method TEXT
);


INSERT INTO customers VALUES
(1, 'Aarav', 'Delhi', 'aarav@example.com', 'premium'),
(2, 'Riya', 'Mumbai', 'riya@example.com', 'standard'),
(3, 'Anez', 'Pune', NULL, 'standard'),
(4, 'Kabir', 'Bangalore', 'kabir@example.com', 'premium'),
(5, 'Meera', 'Delhi', NULL, 'standard'),
(6, 'Ariz', 'Chennai', 'ariz@example.com', 'premium'),
(7, 'Zoe', 'Hyderabad', 'zoe@example.com', 'standard');


INSERT INTO orders VALUES
(1001, 1, '2026-01-01', 2500, 'completed', 'NEW10'),
(1002, 2, '2026-01-02', 800, 'completed', NULL),
(1003, 3, '2026-01-03', 1200, 'pending', 'SAVE5'),
(1004, 4, '2026-01-04', 0, 'complted', NULL),
(1005, 99, '2026-01-05', 1500, 'completed', NULL),
(1006, 5, '2026-01-06', 450, 'cancelled', 'TEST'),
(1007, 6, '2026-01-07', 3200, 'completed', 'VIP'),
(1008, 7, '2026-01-08', NULL, 'completed', NULL);


INSERT INTO payments VALUES
(9001, 1001, 'success', 'card'),
(9002, 1002, 'success', 'upi'),
(9003, 1003, 'pending', 'card'),
(9004, 1005, 'success', 'wallet'),
(9005, 1007, 'failed', 'card');
""")


conn.commit()
q("SELECT * FROM orders")

   order_id  customer_id  order_date  amount     status coupon_code
0      1001            1  2026-01-01  2500.0  completed       NEW10
1      1002            2  2026-01-02   800.0  completed        None
2      1003            3  2026-01-03  1200.0    pending       SAVE5
3      1004            4  2026-01-04     0.0   complted        None
4      1005           99  2026-01-05  1500.0  completed        None
5      1006            5  2026-01-06   450.0  cancelled        TEST
6      1007            6  2026-01-07  3200.0  completed         VIP
7      1008            7  2026-01-08     NaN  completed        None

In [2]:
q("SELECT * FROM payments")

   payment_id  order_id payment_status payment_method
0        9001      1001        success           card
1        9002      1002        success            upi
2        9003      1003        pending           card
3        9004      1005        success         wallet
4        9005      1007         failed           card

In [5]:
q("SELECT * FROM customers")

   customer_id customer_name       city              email   segment
0            1         Aarav      Delhi  aarav@example.com   premium
1            2          Riya     Mumbai   riya@example.com  standard
2            3          Anez       Pune               None  standard
3            4         Kabir  Bangalore  kabir@example.com   premium
4            5         Meera      Delhi               None  standard
5            6          Ariz    Chennai   ariz@example.com   premium
6            7           Zoe  Hyderabad    zoe@example.com  standard
7            8          Anuz     Jaipur               None   premium

--------------------------------------------------------------------------------
# **Part A - DML Task**
--------------------------------------------------------------------------------
### Important safety rule: before every UPDATE or DELETE, first run a SELECT query with the same WHERE condition to preview the rows that will be changed.
-------------------------------------------------------------------------------
## **Task Requirement**
-------------------------------------------------------------------------------

### A1 Single insert: add one new customer with name Anuz, city Jaipur, segment premium.

In [18]:
# CREATE TABLE customers (
#  customer_id INTEGER PRIMARY KEY,
#  customer_name TEXT,
#  city TEXT,
#  email TEXT,
#  segment TEXT
# );

In [6]:
cur.executescript(
    """
    insert into customers (customer_name, city, segment)
    values ('Anuz', 'Jaipur', 'premium');
    """
)

In [10]:
cur.executescript("""delete from customers where customer_id = 9;""")

In [11]:
q("select * from customers")

   customer_id customer_name       city              email   segment
0            1         Aarav      Delhi  aarav@example.com   premium
1            2          Riya     Mumbai   riya@example.com  standard
2            3          Anez       Pune               None  standard
3            4         Kabir  Bangalore  kabir@example.com   premium
4            5         Meera      Delhi               None  standard
5            6          Ariz    Chennai   ariz@example.com   premium
6            7           Zoe  Hyderabad    zoe@example.com  standard
7            8          Anuz     Jaipur               None   premium

### A2 Bulk insert: insert three new orders using executemany(). Include one completed, one pending, and one cancelled order.

In [12]:
# CREATE TABLE orders (
#  order_id INTEGER PRIMARY KEY,
#  customer_id INTEGER,
#  order_date TEXT,
#  amount REAL,
#  status TEXT,
#  coupon_code TEXT
# );

In [14]:

new_order_data = [(1009, 9, '2026-01-10', 2800, 'completed', 'NEW10'),
                  (1010, 10, '2026-01-11', 1000, 'pending', 'NULL'),
                  (1011, 11, '2026-01-12', 800, 'cancelled', 'SAVE5')]

insert_sql = "INSERT INTO orders VALUES (?, ?, ?, ?, ?, ?)"

cur.executemany(insert_sql, new_order_data)
conn.commit()

In [15]:
q("select * from orders")

    order_id  customer_id  order_date  amount     status coupon_code
0       1001            1  2026-01-01  2500.0  completed       NEW10
1       1002            2  2026-01-02   800.0  completed        None
2       1003            3  2026-01-03  1200.0    pending       SAVE5
3       1004            4  2026-01-04     0.0   complted        None
4       1005           99  2026-01-05  1500.0  completed        None
5       1006            5  2026-01-06   450.0  cancelled        TEST
6       1007            6  2026-01-07  3200.0  completed         VIP
7       1008            7  2026-01-08     NaN  completed        None
8       1009            9  2026-01-10  2800.0  completed       NEW10
9       1010           10  2026-01-11  1000.0    pending        NULL
10      1011           11  2026-01-12   800.0  cancelled       SAVE5

### A3 Update: fix the typo status 'complted' to 'completed' only for the affected row.

In [16]:
cur.executescript("""
update orders
set status = 'completed'
where status = 'complted';
"""
)

In [17]:
q("select * from orders")

    order_id  customer_id  order_date  amount     status coupon_code
0       1001            1  2026-01-01  2500.0  completed       NEW10
1       1002            2  2026-01-02   800.0  completed        None
2       1003            3  2026-01-03  1200.0    pending       SAVE5
3       1004            4  2026-01-04     0.0  completed        None
4       1005           99  2026-01-05  1500.0  completed        None
5       1006            5  2026-01-06   450.0  cancelled        TEST
6       1007            6  2026-01-07  3200.0  completed         VIP
7       1008            7  2026-01-08     NaN  completed        None
8       1009            9  2026-01-10  2800.0  completed       NEW10
9       1010           10  2026-01-11  1000.0    pending        NULL
10      1011           11  2026-01-12   800.0  cancelled       SAVE5

### A4 Update: fill missing email for customer_id = 3. Do not update all customers.

In [21]:
cur.executescript("""
update customers
set email = "anez@example.com"
where customer_id = 3;
"""
)

In [22]:
q("select * from customers where customer_id = 3")

   customer_id customer_name  city             email   segment
0            3          Anez  Pune  anez@example.com  standard

### A5 Delete: remove only cancelled test orders where status = 'cancelled' and coupon_code = 'TEST'.

In [23]:
cur.executescript("""
delete from orders
where status = "cancelled" and coupon_code = "TEST";
""")

In [24]:
q("select * from orders")

   order_id  customer_id  order_date  amount     status coupon_code
0      1001            1  2026-01-01  2500.0  completed       NEW10
1      1002            2  2026-01-02   800.0  completed        None
2      1003            3  2026-01-03  1200.0    pending       SAVE5
3      1004            4  2026-01-04     0.0  completed        None
4      1005           99  2026-01-05  1500.0  completed        None
5      1007            6  2026-01-07  3200.0  completed         VIP
6      1008            7  2026-01-08     NaN  completed        None
7      1009            9  2026-01-10  2800.0  completed       NEW10
8      1010           10  2026-01-11  1000.0    pending        NULL
9      1011           11  2026-01-12   800.0  cancelled       SAVE5

### A6 Verification: after each DML step, show the changed rows using SELECT.

In [25]:
q("select * from customers")

   customer_id customer_name       city              email   segment
0            1         Aarav      Delhi  aarav@example.com   premium
1            2          Riya     Mumbai   riya@example.com  standard
2            3          Anez       Pune   anez@example.com  standard
3            4         Kabir  Bangalore  kabir@example.com   premium
4            5         Meera      Delhi               None  standard
5            6          Ariz    Chennai   ariz@example.com   premium
6            7           Zoe  Hyderabad    zoe@example.com  standard
7            8          Anuz     Jaipur               None   premium

In [26]:
q("select * from orders")

   order_id  customer_id  order_date  amount     status coupon_code
0      1001            1  2026-01-01  2500.0  completed       NEW10
1      1002            2  2026-01-02   800.0  completed        None
2      1003            3  2026-01-03  1200.0    pending       SAVE5
3      1004            4  2026-01-04     0.0  completed        None
4      1005           99  2026-01-05  1500.0  completed        None
5      1007            6  2026-01-07  3200.0  completed         VIP
6      1008            7  2026-01-08     NaN  completed        None
7      1009            9  2026-01-10  2800.0  completed       NEW10
8      1010           10  2026-01-11  1000.0    pending        NULL
9      1011           11  2026-01-12   800.0  cancelled       SAVE5

--------------------------------------------------------------------------------
# **Part B - SELECT Pipeline Tasks**
-------------------------------------------------------------------------------
## **Task Requirement**
-------------------------------------------------------------------------------

### B1 Show all rows from customers, orders, and payments using SELECT *.

In [27]:
q("select * from customers")

   customer_id customer_name       city              email   segment
0            1         Aarav      Delhi  aarav@example.com   premium
1            2          Riya     Mumbai   riya@example.com  standard
2            3          Anez       Pune   anez@example.com  standard
3            4         Kabir  Bangalore  kabir@example.com   premium
4            5         Meera      Delhi               None  standard
5            6          Ariz    Chennai   ariz@example.com   premium
6            7           Zoe  Hyderabad    zoe@example.com  standard
7            8          Anuz     Jaipur               None   premium

In [28]:
q("select * from orders")

   order_id  customer_id  order_date  amount     status coupon_code
0      1001            1  2026-01-01  2500.0  completed       NEW10
1      1002            2  2026-01-02   800.0  completed        None
2      1003            3  2026-01-03  1200.0    pending       SAVE5
3      1004            4  2026-01-04     0.0  completed        None
4      1005           99  2026-01-05  1500.0  completed        None
5      1007            6  2026-01-07  3200.0  completed         VIP
6      1008            7  2026-01-08     NaN  completed        None
7      1009            9  2026-01-10  2800.0  completed       NEW10
8      1010           10  2026-01-11  1000.0    pending        NULL
9      1011           11  2026-01-12   800.0  cancelled       SAVE5

In [29]:
q("select * from payments")

   payment_id  order_id payment_status payment_method
0        9001      1001        success           card
1        9002      1002        success            upi
2        9003      1003        pending           card
3        9004      1005        success         wallet
4        9005      1007         failed           card

### B2 Select only useful order columns: order_id, customer_id, amount, status.

In [30]:
q("select order_id, customer_id, amount, status from orders")

   order_id  customer_id  amount     status
0      1001            1  2500.0  completed
1      1002            2   800.0  completed
2      1003            3  1200.0    pending
3      1004            4     0.0  completed
4      1005           99  1500.0  completed
5      1007            6  3200.0  completed
6      1008            7     NaN  completed
7      1009            9  2800.0  completed
8      1010           10  1000.0    pending
9      1011           11   800.0  cancelled

### B3 Use DISTINCT to list unique cities, order statuses, and payment statuses.

In [32]:
q("select distinct city as List_of_Unique_Cities from customers")

  List_of_Unique_Cities
0                 Delhi
1                Mumbai
2                  Pune
3             Bangalore
4               Chennai
5             Hyderabad
6                Jaipur

### B4 Use column aliases: amount AS order_amount, status AS order_status.

In [37]:
q("select amount as order_amount, status as order_status from orders;")

   order_amount order_status
0        2500.0    completed
1         800.0    completed
2        1200.0      pending
3           0.0    completed
4        1500.0    completed
5        3200.0    completed
6           NaN    completed
7        2800.0    completed
8        1000.0      pending
9         800.0    cancelled

### B5 Use table aliases while querying customers and orders.

In [41]:
q("select * from customers as c1 left join orders as o1 on c1.customer_id = o1.customer_id")

,customer_id,customer_name,city,email,segment,order_id,customer_id,order_date,amount,status,coupon_code
0,1,Aarav,Delhi,aarav@example.com,premium,1001.0,1.0,2026-01-01,2500.0,completed,NEW10
1,2,Riya,Mumbai,riya@example.com,standard,1002.0,2.0,2026-01-02,800.0,completed,None
2,3,Anez,Pune,anez@example.com,standard,1003.0,3.0,2026-01-03,1200.0,pending,SAVE5
3,4,Kabir,Bangalore,kabir@example.com,premium,1004.0,4.0,2026-01-04,0.0,completed,None
4,5,Meera,Delhi,None,standard,NaN,NaN,None,NaN,None,None
5,6,Ariz,Chennai,ariz@example.com,premium,1007.0,6.0,2026-01-07,3200.0,completed,VIP
6,7,Zoe,Hyderabad,zoe@example.com,standard,1008.0,7.0,2026-01-08,NaN,completed,None
7,8,Anuz,Jaipur,None,premium,NaN,NaN,None,NaN,None,None

### B6 Create a derived column: amount * 1.18 AS amount_with_gst for completed orders.

In [42]:
cur.executescript("""
alter table orders
add column amount_with_gst real;
""")

In [43]:
cur.executescript("""
update orders
set amount_with_gst = amount * 1.18
where status = "completed";
""")

In [45]:
q("select * from orders")

,order_id,customer_id,order_date,amount,status,coupon_code,amount_with_gst
0,1001,1,2026-01-01,2500.0,completed,NEW10,2950.0
1,1002,2,2026-01-02,800.0,completed,None,944.0
2,1003,3,2026-01-03,1200.0,pending,SAVE5,NaN
3,1004,4,2026-01-04,0.0,completed,None,0.0
4,1005,99,2026-01-05,1500.0,completed,None,1770.0
5,1007,6,2026-01-07,3200.0,completed,VIP,3776.0
6,1008,7,2026-01-08,NaN,completed,None,NaN
7,1009,9,2026-01-10,2800.0,completed,NEW10,3304.0
8,1010,10,2026-01-11,1000.0,pending,NULL,NaN
9,1011,11,2026-01-12,800.0,cancelled,SAVE5,NaN

--------------------------------------------------------------------------------
# **Part C - Filtering Logic Tasks**
-------------------------------------------------------------------------------
## **Task Requirement**
-------------------------------------------------------------------------------

### C1 Use AND: completed orders where amount > 1000.

In [46]:
q("select * from orders where status = 'completed' and amount > 1000")

,order_id,customer_id,order_date,amount,status,coupon_code,amount_with_gst
0,1001,1,2026-01-01,2500.0,completed,NEW10,2950.0
1,1005,99,2026-01-05,1500.0,completed,None,1770.0
2,1007,6,2026-01-07,3200.0,completed,VIP,3776.0
3,1009,9,2026-01-10,2800.0,completed,NEW10,3304.0

### C2 Use OR: orders that are pending or failed/cancelled style records.

In [47]:
q("select * from orders where status = 'pending' or status = 'cancelled'")

,order_id,customer_id,order_date,amount,status,coupon_code,amount_with_gst
0,1003,3,2026-01-03,1200.0,pending,SAVE5,None
1,1010,10,2026-01-11,1000.0,pending,NULL,None
2,1011,11,2026-01-12,800.0,cancelled,SAVE5,None

### C3 Use NOT: orders where status is not completed.

In [48]:
q("select * from orders where not status = 'completed'")

,order_id,customer_id,order_date,amount,status,coupon_code,amount_with_gst
0,1003,3,2026-01-03,1200.0,pending,SAVE5,None
1,1010,10,2026-01-11,1000.0,pending,NULL,None
2,1011,11,2026-01-12,800.0,cancelled,SAVE5,None

### C4 Use IN: customers from Delhi, Mumbai, or Chennai.

In [49]:
q("select * from customers where city in ('Delhi', 'Mumbai', 'Chennai')")

   customer_id customer_name     city              email   segment
0            1         Aarav    Delhi  aarav@example.com   premium
1            2          Riya   Mumbai   riya@example.com  standard
2            5         Meera    Delhi               None  standard
3            6          Ariz  Chennai   ariz@example.com   premium

### C5 Use BETWEEN: orders between 500 and 2500 amount.

In [51]:
q("select * from orders where amount between 500 and 2500")

,order_id,customer_id,order_date,amount,status,coupon_code,amount_with_gst
0,1001,1,2026-01-01,2500.0,completed,NEW10,2950.0
1,1002,2,2026-01-02,800.0,completed,None,944.0
2,1003,3,2026-01-03,1200.0,pending,SAVE5,NaN
3,1005,99,2026-01-05,1500.0,completed,None,1770.0
4,1010,10,2026-01-11,1000.0,pending,NULL,NaN
5,1011,11,2026-01-12,800.0,cancelled,SAVE5,NaN

### C6 Use BETWEEN for dates: orders from 2026-01-02 to 2026-01-07.

In [52]:
q("select * from orders where order_date between '2026-01-02' and '2026-01-07'")

,order_id,customer_id,order_date,amount,status,coupon_code,amount_with_gst
0,1002,2,2026-01-02,800.0,completed,None,944.0
1,1003,3,2026-01-03,1200.0,pending,SAVE5,NaN
2,1004,4,2026-01-04,0.0,completed,None,0.0
3,1005,99,2026-01-05,1500.0,completed,None,1770.0
4,1007,6,2026-01-07,3200.0,completed,VIP,3776.0

### C7 Use LIKE: customers whose name starts with 'A' and ends with 'z'.

In [53]:
q("select * from customers where customer_name like 'A%z'")

   customer_id customer_name     city             email   segment
0            3          Anez     Pune  anez@example.com  standard
1            6          Ariz  Chennai  ariz@example.com   premium
2            8          Anuz   Jaipur              None   premium

### C8 Use LIKE with wildcard _: customers whose name has exactly 4 characters.

In [54]:
q("select * from customers where customer_name like '____'")

   customer_id customer_name     city             email   segment
0            2          Riya   Mumbai  riya@example.com  standard
1            3          Anez     Pune  anez@example.com  standard
2            6          Ariz  Chennai  ariz@example.com   premium
3            8          Anuz   Jaipur              None   premium

### C9 Use IS NULL: customers with missing email and orders with missing amount.

In [58]:
q("select * from customers where email is null")

   customer_id customer_name    city email   segment
0            5         Meera   Delhi  None  standard
1            8          Anuz  Jaipur  None   premium

In [59]:
q("select * from orders where amount is null")

,order_id,customer_id,order_date,amount,status,coupon_code,amount_with_gst
0,1008,7,2026-01-08,None,completed,None,None

### C10 Use IS NOT NULL: orders where coupon_code is present.

In [61]:
q("select * from orders where coupon_code IS NOT NULL")

,order_id,customer_id,order_date,amount,status,coupon_code,amount_with_gst
0,1001,1,2026-01-01,2500.0,completed,NEW10,2950.0
1,1003,3,2026-01-03,1200.0,pending,SAVE5,NaN
2,1007,6,2026-01-07,3200.0,completed,VIP,3776.0
3,1009,9,2026-01-10,2800.0,completed,NEW10,3304.0
4,1010,10,2026-01-11,1000.0,pending,NULL,NaN
5,1011,11,2026-01-12,800.0,cancelled,SAVE5,NaN

--------------------------------------------------------------------------------
# **Part D - Data Engineering Validation Queries**
--------------------------------------------------------------------------------
### Write SQL queries for the following checks. These are common data validation checks in ETL pipelines.
-------------------------------------------------------------------------------
## **Task Requirement**
-------------------------------------------------------------------------------

### D1 Find invalid foreign keys: orders.customer_id values not present in customers.customer_id

In [62]:
q("SELECT DISTINCT o.customer_id FROM orders o LEFT JOIN customers c ON o.customer_id = c.customer_id WHERE c.customer_id IS NULL;")

   customer_id
0           99
1            9
2           10
3           11

### D2 Find successful payments for orders that are not completed.

In [72]:
q("select * from payments where payment_status = 'success' and order_id in (select order_id from orders where status != 'completed');")

Empty DataFrame
Columns: [payment_id, order_id, payment_status, payment_method]
Index: []

In [70]:
q("select * from orders as o left join payments as p on o.order_id = p.order_id where o.status is not 'completed' and p.payment_status is 'success'")

Empty DataFrame
Columns: [order_id, customer_id, order_date, amount, status, coupon_code, amount_with_gst, payment_id, order_id, payment_status, payment_method]
Index: []

### D3 Find completed orders with NULL amount or amount <= 0.

In [73]:
q("select * from orders where status = 'completed' and (amount is null or amount <= 0);")

,order_id,customer_id,order_date,amount,status,coupon_code,amount_with_gst
0,1004,4,2026-01-04,0.0,completed,None,0.0
1,1008,7,2026-01-08,NaN,completed,None,NaN

### D4 Find customers who have no orders.

In [74]:
q("select * from customers where customer_id not in (select customer_id from orders);")

   customer_id customer_name    city email   segment
0            5         Meera   Delhi  None  standard
1            8          Anuz  Jaipur  None   premium

### D5 Create a final clean order view using only valid completed orders with valid customers and non-null positive amount.

In [75]:
q("select * from orders where status = 'completed' and customer_id in (select customer_id from customers) and amount is not null and amount > 0;")

,order_id,customer_id,order_date,amount,status,coupon_code,amount_with_gst
0,1001,1,2026-01-01,2500.0,completed,NEW10,2950.0
1,1002,2,2026-01-02,800.0,completed,None,944.0
2,1007,6,2026-01-07,3200.0,completed,VIP,3776.0

--------------------------------------------------------------------------------
# **Part E - Final Business Report**
--------------------------------------------------------------------------------
### Create one final SQL report with the following columns. Use aliases to make the output readable.
-------------------------------------------------------------------------------
### **customer_id**
### **customer_name**
### **city**
### **total_completed_orders**
### **total_revenue**
### **average_order_value**
-------------------------------------------------------------------------------

In [76]:
q("""
SELECT
    c.customer_id AS customer_id,
    c.customer_name AS customer_name,
    c.city AS city,
    COUNT(o.order_id) AS total_completed_orders,
    SUM(o.amount) AS total_revenue,
    AVG(o.amount) AS average_order_value
FROM
    customers AS c
JOIN
    orders AS o ON c.customer_id = o.customer_id
WHERE
    o.status = 'completed'
    AND o.amount IS NOT NULL
    AND o.amount > 0
GROUP BY
    c.customer_id, c.customer_name, c.city
ORDER BY
    total_revenue DESC;
""")

,customer_id,customer_name,city,total_completed_orders,total_revenue,average_order_value
0,6,Ariz,Chennai,1,3200.0,3200.0
1,1,Aarav,Delhi,1,2500.0,2500.0
2,2,Riya,Mumbai,1,800.0,800.0

## Required Interview Answers

### What is the execution order of a SQL query? Explain FROM, WHERE, SELECT, ORDER BY in simple terms.

The logical execution order of a SQL query is generally as follows, though the database optimizer might physically execute it differently:

1.  **FROM**: Identifies the tables involved in the query and how they are joined.
    *   **Simple term**: This is where you tell the database *which tables to look at*.
2.  **WHERE**: Filters rows based on specified conditions.
    *   **Simple term**: This is where you tell the database *which rows to keep* based on certain criteria.
3.  **GROUP BY**: Groups rows that have the same values in specified columns into summary rows.
    *   **Simple term**: This is where you tell the database to *combine similar rows* for aggregation (e.g., sum, count).
4.  **HAVING**: Filters groups based on specified conditions, similar to WHERE but for grouped data.
    *   **Simple term**: This is where you tell the database *which combined groups to keep*.
5.  **SELECT**: Specifies which columns or expressions to return.
    *   **Simple term**: This is where you tell the database *what information to show* from the kept rows/groups.
6.  **ORDER BY**: Sorts the result set based on specified columns.
    *   **Simple term**: This is where you tell the database *how to sort the final results*.

### How do you find all records where the name starts with 'A' and ends with 'Z' or 'z'?

You would use the `LIKE` operator with wildcards. For example:

```sql
SELECT * FROM customers
WHERE customer_name LIKE 'A%Z' OR customer_name LIKE 'A%z';
```

### Why should NULL values be handled using IS NULL instead of = NULL?

`NULL` in SQL represents an unknown or missing value, not a specific data value. Therefore, it cannot be directly compared using standard comparison operators like `=`. The expression `NULL = NULL` does not evaluate to true; instead, it evaluates to `UNKNOWN` (or `NULL` depending on context and SQL dialect). To correctly check for the presence or absence of a `NULL` value, you must use the special operators `IS NULL` or `IS NOT NULL`.

### Why is UPDATE or DELETE without WHERE dangerous in production databases?

Using `UPDATE` or `DELETE` statements without a `WHERE` clause is extremely dangerous in a production database because:

*   **UPDATE without WHERE**: It will modify *every single row* in the specified table. This can lead to mass data corruption, changing all values in a column or set of columns across the entire table, making it unusable and potentially violating data integrity rules.
*   **DELETE without WHERE**: It will delete *every single row* from the specified table. This results in the complete loss of all data in that table, which can be catastrophic for an application or business process that relies on that data. Recovery typically requires restoring from a backup, leading to significant downtime and potential data loss since the last backup.