# Day 27 - Pandas Fundamentals and Data Loading

This notebook covers:
- Pandas Series
- Pandas DataFrame
- Reading CSV, JSON, Excel, and Parquet files
- Writing Parquet files
- Data inspection with head(), info(), describe(), and shape
- Indexing and selection with loc and iloc
- Boolean indexing
- Data engineering examples
- Interview questions

## 1. Import Libraries

In [ ]:
import pandas as pd
import numpy as np

print("pandas version:", pd.__version__)

pandas version: 2.2.2

## 2. Series: 1D Labeled Array

A Series is a one-dimensional labeled array.

It can be used to represent one column of data.

In [ ]:
sales_series = pd.Series([1000, 1500, 1200, 1800], name="sales")

print(sales_series)
print(type(sales_series))

0    1000
1    1500
2    1200
3    1800
Name: sales, dtype: int64
<class 'pandas.core.series.Series'>

## 3. Series with Custom Index

In [ ]:
daily_sales = pd.Series(
    data=[1000, 1500, 1200, 1800],
    index=["Monday", "Tuesday", "Wednesday", "Thursday"],
    name="daily_sales"
)

print(daily_sales)
print(daily_sales["Tuesday"])

Monday       1000
Tuesday      1500
Wednesday    1200
Thursday     1800
Name: daily_sales, dtype: int64
1500

## 4. DataFrame: 2D Tabular Structure

A DataFrame is a two-dimensional table with rows and columns.

It is the most commonly used Pandas object in data analysis and data engineering.

In [ ]:
orders_df = pd.DataFrame({
    "order_id": [1001, 1002, 1003, 1004],
    "customer_id": [501, 502, 503, 501],
    "amount": [250.50, -100.00, 500.00, 1200.00],
    "status": ["completed", "completed", "pending", "completed"]
})

print(orders_df)
print(type(orders_df))

   order_id  customer_id  amount     status
0      1001          501   250.5  completed
1      1002          502  -100.0  completed
2      1003          503   500.0    pending
3      1004          501  1200.0  completed
<class 'pandas.core.frame.DataFrame'>

## 5. Selecting a Column Returns a Series

In [ ]:
amount_series = orders_df["amount"]

print(amount_series)
print(type(amount_series))

0     250.5
1    -100.0
2     500.0
3    1200.0
Name: amount, dtype: float64
<class 'pandas.core.series.Series'>

## 6. Selecting Multiple Columns Returns a DataFrame

In [ ]:
selected_columns = orders_df[["order_id", "amount"]]

print(selected_columns)
print(type(selected_columns))

   order_id  amount
0      1001   250.5
1      1002  -100.0
2      1003   500.0
3      1004  1200.0
<class 'pandas.core.frame.DataFrame'>

# Creating Sample Files for Data Loading

## 7. Create Sample CSV File

In [ ]:
orders_data = pd.DataFrame({
    "order_id": [1001, 1002, 1003, 1004, 1005, 1006],
    "customer_id": [501, 502, 503, 501, 504, 505],
    "amount": [250.50, -100.00, 500.00, 1200.00, 0.00, 750.00],
    "status": ["completed", "completed", "pending", "completed", "completed", "completed"],
    "city": ["Delhi", "Mumbai", "Bangalore", "Delhi", "Pune", "Chennai"]
})

orders_data.to_csv("orders.csv", index=False)

print("orders.csv created")

orders.csv created

## 8. Create Sample JSON File

In [ ]:
products_data = pd.DataFrame({
    "product_id": [201, 202, 203, 204],
    "product_name": ["Laptop", "Phone", "Shoes", "Keyboard"],
    "category": ["Electronics", "Electronics", "Fashion", "Electronics"],
    "price": [80000, 40000, 3000, 1500],
    "stock": [15, 5, 50, 8]
})

products_data.to_json("products.json", orient="records", indent=2)

print("products.json created")

products.json created

## 9. Create Sample Excel File

Excel support requires openpyxl.

If needed, install it using:

```python
!pip install openpyxl
```

In [ ]:
customers_data = pd.DataFrame({
    "customer_id": [501, 502, 503, 504, 505],
    "customer_name": ["Riya", "Aarav", "Kabir", "Meera", "Isha"],
    "segment": ["Premium", "Standard", "Standard", "Premium", "Standard"],
    "city": ["Delhi", "Mumbai", "Bangalore", "Pune", "Chennai"]
})

try:
    customers_data.to_excel("customers.xlsx", index=False)
    print("customers.xlsx created")
except Exception as error:
    print("Excel write failed. Install openpyxl if needed: !pip install openpyxl")
    print(error)

customers.xlsx created

## 10. Create Sample Parquet File

Parquet support requires pyarrow or fastparquet.

In Google Colab, pyarrow is usually available.

If needed, install it using:

```python
!pip install pyarrow
```

In [ ]:
try:
    orders_data.to_parquet("orders.parquet", index=False)
    print("orders.parquet created")
except Exception as error:
    print("Parquet write failed. Install pyarrow if needed: !pip install pyarrow")
    print(error)

orders.parquet created

# Data Ingestion

## 11. Read CSV File

In [ ]:
orders_csv = pd.read_csv("orders.csv")

print(orders_csv)

   order_id  customer_id  amount     status       city
0      1001          501   250.5  completed      Delhi
1      1002          502  -100.0  completed     Mumbai
2      1003          503   500.0    pending  Bangalore
3      1004          501  1200.0  completed      Delhi
4      1005          504     0.0  completed       Pune
5      1006          505   750.0  completed    Chennai

## 12. Read JSON File

In [ ]:
products_json = pd.read_json("products.json")

print(products_json)

   product_id product_name     category  price  stock
0         201       Laptop  Electronics  80000     15
1         202        Phone  Electronics  40000      5
2         203        Shoes      Fashion   3000     50
3         204     Keyboard  Electronics   1500      8

## 13. Read Excel File

In [ ]:
try:
    customers_excel = pd.read_excel("customers.xlsx")
    print(customers_excel)
except Exception as error:
    print("Excel read failed. Install openpyxl if needed: !pip install openpyxl")
    print(error)

   customer_id customer_name   segment       city
0          501          Riya   Premium      Delhi
1          502         Aarav  Standard     Mumbai
2          503         Kabir  Standard  Bangalore
3          504         Meera   Premium       Pune
4          505          Isha  Standard    Chennai

## 14. Read Parquet File

In [ ]:
try:
    orders_parquet = pd.read_parquet("orders.parquet")
    print(orders_parquet)
except Exception as error:
    print("Parquet read failed. Install pyarrow if needed: !pip install pyarrow")
    print(error)

   order_id  customer_id  amount     status       city
0      1001          501   250.5  completed      Delhi
1      1002          502  -100.0  completed     Mumbai
2      1003          503   500.0    pending  Bangalore
3      1004          501  1200.0  completed      Delhi
4      1005          504     0.0  completed       Pune
5      1006          505   750.0  completed    Chennai

## 15. Write Clean Data to Parquet

Parquet is commonly used in data engineering because it is columnar, compressed, and efficient for analytics.

In [ ]:
valid_orders = orders_csv[
    (orders_csv["amount"] > 0) &
    (orders_csv["status"] == "completed")
]

try:
    valid_orders.to_parquet("valid_orders.parquet", index=False)
    print("valid_orders.parquet created")
except Exception as error:
    print("Parquet write failed. Install pyarrow if needed: !pip install pyarrow")
    print(error)

valid_orders.parquet created

# Data Inspection

## 16. head()

head() shows the first few rows of a DataFrame.

In [ ]:
orders_csv.head()

   order_id  customer_id  amount     status       city
0      1001          501   250.5  completed      Delhi
1      1002          502  -100.0  completed     Mumbai
2      1003          503   500.0    pending  Bangalore
3      1004          501  1200.0  completed      Delhi
4      1005          504     0.0  completed       Pune

## 17. shape

shape returns the number of rows and columns.

In [ ]:
print(orders_csv.shape)

rows, columns = orders_csv.shape

print("rows:", rows)
print("columns:", columns)

(6, 5)
rows: 6
columns: 5

## 18. info()

info() shows column names, non-null counts, and data types.

In [ ]:
orders_csv.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 6 entries, 0 to 5
Data columns (total 5 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   order_id     6 non-null      int64
 1   customer_id  6 non-null      int64
 2   amount       6 non-null      float64
 3   status       6 non-null      object
 4   city         6 non-null      object
dtypes: float64(1), int64(2), object(2)
memory usage: 372.0+ bytes

## 19. describe()

describe() gives summary statistics for numeric columns.

In [ ]:
orders_csv.describe()

          order_id  customer_id       amount
count     6.000000     6.000000     6.000000
mean   1003.500000   502.666667   433.416667
std       1.870829     1.632993   489.520216
min    1001.000000   501.000000  -100.000000
25%    1002.250000   501.250000    62.625000
50%    1003.500000   502.500000   375.250000
75%    1004.750000   503.750000   687.500000
max    1006.000000   505.000000  1200.000000

## 20. Inspect Columns and Data Types

In [ ]:
print(orders_csv.columns)
print(orders_csv.dtypes)

Index(['order_id', 'customer_id', 'amount', 'status', 'city'], dtype='object')
order_id         int64
customer_id      int64
amount         float64
status          object
city            object
dtype: object

## 21. Data Engineering Quick Dataset Check

Useful checks after loading a new dataset:
- number of rows
- number of columns
- column names
- data types
- missing values

In [ ]:
print("Shape:", orders_csv.shape)
print("Columns:", list(orders_csv.columns))
print("Data types:")
print(orders_csv.dtypes)

print("Missing values:")
print(orders_csv.isna().sum())

Shape: (6, 5)
Columns: ['order_id', 'customer_id', 'amount', 'status', 'city']
Data types:
order_id         int64
customer_id      int64
amount         float64
status          object
city            object
dtype: object
Missing values:
order_id       0
customer_id    0
amount         0
status         0
city           0
dtype: int64

# Indexing and Selection

## 22. Selecting One Column

In [ ]:
amount = orders_csv["amount"]
amount

0     250.5
1    -100.0
2     500.0
3    1200.0
4       0.0
5     750.0
Name: amount, dtype: float64

In [ ]:
# type(amount)

## 23. Selecting Multiple Columns

In [ ]:
orders_csv[["order_id", "customer_id", "amount"]]

   order_id  customer_id  amount
0      1001          501   250.5
1      1002          502  -100.0
2      1003          503   500.0
3      1004          501  1200.0
4      1005          504     0.0
5      1006          505   750.0

## 24. iloc: Integer Position Based Selection

iloc selects rows and columns by integer position.

In [ ]:
print(orders_csv.iloc[0])

order_id            1001
customer_id          501
amount             250.5
status         completed
city               Delhi
Name: 0, dtype: object

In [ ]:
print(orders_csv.iloc[0:3])

   order_id  customer_id  amount     status       city
0      1001          501   250.5  completed      Delhi
1      1002          502  -100.0  completed     Mumbai
2      1003          503   500.0    pending  Bangalore

In [ ]:
print(orders_csv.iloc[0:3, 0:2])

   order_id  customer_id
0      1001          501
1      1002          502
2      1003          503

## 25. loc: Label Based Selection

loc selects rows and columns by labels.

In [ ]:
print(orders_csv.loc[0])
print(orders_csv.loc[0:3, ["order_id", "amount", "status"]])

order_id            1001
customer_id          501
amount             250.5
status         completed
city               Delhi
Name: 0, dtype: object
   order_id  amount     status
0      1001   250.5  completed
1      1002  -100.0  completed
2      1003   500.0    pending
3      1004  1200.0  completed

## 26. Difference Between loc and iloc

In [ ]:
print("Using iloc:")
print(orders_csv.iloc[0:3, 0:2])

print("Using loc:")
print(orders_csv.loc[0:3, ["order_id", "customer_id"]])

Using iloc:
   order_id  customer_id
0      1001          501
1      1002          502
2      1003          503
Using loc:
   order_id  customer_id
0      1001          501
1      1002          502
2      1003          503
3      1004          501

## 27. Set a Custom Index

In [ ]:
orders_by_id = orders_csv.set_index("order_id")

print(orders_by_id)

          customer_id  amount     status       city
order_id
1001              501   250.5  completed      Delhi
1002              502  -100.0  completed     Mumbai
1003              503   500.0    pending  Bangalore
1004              501  1200.0  completed      Delhi
1005              504     0.0  completed       Pune
1006              505   750.0  completed    Chennai

## 28. loc with Custom Index

In [ ]:
print(orders_by_id.loc[1001])
print(orders_by_id.loc[[1001, 1004]])

customer_id          501
amount             250.5
status         completed
city               Delhi
Name: 1001, dtype: object
          customer_id  amount     status   city
order_id
1001              501   250.5  completed  Delhi
1004              501  1200.0  completed  Delhi

## 29. iloc with Custom Index

iloc still uses integer position, even if the DataFrame has a custom index.

In [ ]:
print(orders_by_id.iloc[0])
print(orders_by_id.iloc[0:2])

customer_id          501
amount             250.5
status         completed
city               Delhi
Name: 1001, dtype: object
          customer_id  amount     status    city
order_id
1001              501   250.5  completed   Delhi
1002              502  -100.0  completed  Mumbai

# Boolean Indexing

## 30. Filter Rows Where Amount Is Greater Than 1000

In [ ]:
high_value_orders = orders_csv[orders_csv["amount"] > 1000]

print(high_value_orders)

   order_id  customer_id  amount     status   city
3      1004          501  1200.0  completed  Delhi

## 31. Filter Completed Orders

In [ ]:
completed_orders = orders_csv[orders_csv["status"] == "completed"]

print(completed_orders)

   order_id  customer_id  amount     status     city
0      1001          501   250.5  completed    Delhi
1      1002          502  -100.0  completed   Mumbai
3      1004          501  1200.0  completed    Delhi
4      1005          504     0.0  completed     Pune
5      1006          505   750.0  completed  Chennai

## 32. Filter with Multiple Conditions

Use:
- & for AND
- | for OR
- parentheses around each condition

In [ ]:
valid_completed_orders = orders_csv[
    (orders_csv["amount"] > 0) &
    (orders_csv["status"] == "completed")
]

print(valid_completed_orders)

   order_id  customer_id  amount     status     city
0      1001          501   250.5  completed    Delhi
3      1004          501  1200.0  completed    Delhi
5      1006          505   750.0  completed  Chennai

## 33. OR Condition

In [ ]:
delhi_or_mumbai_orders = orders_csv[
    (orders_csv["city"] == "Delhi") |
    (orders_csv["city"] == "Mumbai")
]

print(delhi_or_mumbai_orders)

   order_id  customer_id  amount     status    city
0      1001          501   250.5  completed   Delhi
1      1002          502  -100.0  completed  Mumbai
3      1004          501  1200.0  completed   Delhi

## 34. Filter Using isin()

In [ ]:
selected_cities = ["Delhi", "Chennai"]

city_orders = orders_csv[orders_csv["city"].isin(selected_cities)]

print(city_orders)

   order_id  customer_id  amount     status     city
0      1001          501   250.5  completed    Delhi
3      1004          501  1200.0  completed    Delhi
5      1006          505   750.0  completed  Chennai

## 35. Data Engineering Use Case: Clean Orders Dataset

Rules:
- amount > 0
- status == completed
- customer_id is not missing

In [ ]:
clean_orders = orders_csv[
    (orders_csv["amount"] > 0) &
    (orders_csv["status"] == "completed") &
    (orders_csv["customer_id"].notna())
]

print(clean_orders)

   order_id  customer_id  amount     status     city
0      1001          501   250.5  completed    Delhi
3      1004          501  1200.0  completed    Delhi
5      1006          505   750.0  completed  Chennai

## 36. Data Engineering Use Case: High Value Customer Orders

In [ ]:
high_value_clean_orders = clean_orders[clean_orders["amount"] >= 700]

print(high_value_clean_orders)

   order_id  customer_id  amount     status     city
3      1004          501  1200.0  completed    Delhi
5      1006          505   750.0  completed  Chennai

# Working with Product Data

## 37. Inspect Product Dataset

In [ ]:
products_json.head()

   product_id product_name     category  price  stock
0         201       Laptop  Electronics  80000     15
1         202        Phone  Electronics  40000      5
2         203        Shoes      Fashion   3000     50
3         204     Keyboard  Electronics   1500      8

## 38. Filter Low Stock Products

In [ ]:
low_stock_products = products_json[products_json["stock"] < 10]

print(low_stock_products)

   product_id product_name     category  price  stock
1         202        Phone  Electronics  40000      5
3         204     Keyboard  Electronics   1500      8

## 39. Filter Electronics Products

In [ ]:
electronics_products = products_json[products_json["category"] == "Electronics"]

print(electronics_products)

   product_id product_name     category  price  stock
0         201       Laptop  Electronics  80000     15
1         202        Phone  Electronics  40000      5
3         204     Keyboard  Electronics   1500      8

## 40. Select Product Names and Prices

In [ ]:
product_price_view = products_json[["product_id", "product_name", "price"]]

print(product_price_view)

   product_id product_name  price
0         201       Laptop  80000
1         202        Phone  40000
2         203        Shoes   3000
3         204     Keyboard   1500

# Working with Customer Data

## 41. Inspect Customer Dataset

In [ ]:
try:
    customers_excel.head()
except NameError:
    print("customers_excel is not available. Run the Excel read cell first.")

## 42. Filter Premium Customers

In [ ]:
try:
    premium_customers = customers_excel[customers_excel["segment"] == "Premium"]
    print(premium_customers)
except NameError:
    print("customers_excel is not available. Run the Excel read cell first.")

   customer_id customer_name  segment   city
0          501          Riya  Premium  Delhi
3          504         Meera  Premium   Pune

# Parquet Context for Data Engineering

## 43. CSV vs Parquet Quick Comparison

CSV:
- row-based text format
- larger file size
- no built-in schema preservation
- slower for analytical column reads

Parquet:
- columnar format
- compressed
- stores schema
- efficient for analytics
- widely used with Spark, Hive, Databricks, BigQuery, Athena, and lakehouse systems

In [ ]:
print("CSV file: orders.csv")
print("Parquet file: orders.parquet or valid_orders.parquet")

CSV file: orders.csv
Parquet file: orders.parquet or valid_orders.parquet

## 44. Compare File Sizes

In [ ]:
from pathlib import Path

csv_size = Path("orders.csv").stat().st_size

print("orders.csv size in bytes:", csv_size)

if Path("orders.parquet").exists():
    parquet_size = Path("orders.parquet").stat().st_size
    print("orders.parquet size in bytes:", parquet_size)
else:
    print("orders.parquet not available")

orders.csv size in bytes: 230
orders.parquet size in bytes: 3417

# Practice Problems

## 45. Practice Problem 1: Series

Create a Pandas Series for daily API request counts.

Use custom index values:
- Monday
- Tuesday
- Wednesday
- Thursday

In [ ]:
# Write solution here

## 46. Practice Problem 2: DataFrame

Create a DataFrame for 5 products with:
- product_id
- name
- price
- stock

In [ ]:
# Write solution here

## 47. Practice Problem 3: Read and Inspect CSV

Read orders.csv and print:
- first 3 rows
- shape
- info
- describe

In [ ]:
# Write solution here

## 48. Practice Problem 4: Filter Orders

Filter rows from orders.csv where:
- amount > 500
- status == completed

In [ ]:
# Write solution here

## 49. Practice Problem 5: loc and iloc

Using orders_csv:
- select first 3 rows using iloc
- select order_id, amount, and status using loc

In [ ]:
# Write solution here

## 50. Practice Problem 6: Parquet

Write clean_orders to a Parquet file and read it back.

In [ ]:
# Write solution here

# Interview Questions

## 51. What is the difference between a Series and a DataFrame?

A Series is a one-dimensional labeled array.

A DataFrame is a two-dimensional tabular structure made of rows and columns.

A single column from a DataFrame is usually a Series.

Multiple columns from a DataFrame form another DataFrame.

## 52. How do you filter a DataFrame to show only rows where Sales > 1000?

Example:

```python
filtered_df = df[df["Sales"] > 1000]
```

For multiple conditions:

```python
filtered_df = df[(df["Sales"] > 1000) & (df["Status"] == "completed")]
```

## 53. Why is Parquet preferred over CSV in Data Engineering pipelines?

Parquet is preferred because:
- it is columnar
- it supports compression
- it stores schema information
- it is faster for analytical queries
- it allows query engines to read only required columns
- it works well with big data tools like Spark, Hive, Databricks, Athena, and lakehouse systems

CSV is simple and readable, but inefficient for large-scale analytics.

## 54. What is the difference between loc and iloc?

loc:
- label-based selection
- uses row labels and column names

iloc:
- integer-position based selection
- uses numeric row and column positions

## 55. Summary

Key takeaways:
- Series is a 1D labeled array.
- DataFrame is a 2D table.
- Pandas can read CSV, JSON, Excel, and Parquet files.
- head(), info(), describe(), and shape help inspect datasets quickly.
- loc is label-based.
- iloc is position-based.
- Boolean indexing filters rows using conditions.
- Parquet is a major file format in modern data engineering.