In [30]:
import requests
import pandas as pd

In [31]:
orders = requests.get("https://fake-store-api.mock.beeceptor.com/api/orders").json()
users = requests.get("https://fake-store-api.mock.beeceptor.com/api/users").json()
products = requests.get("https://fake-store-api.mock.beeceptor.com/api/products").json()

## Orders Data

In [33]:
# Convert to dataframe
df = pd.DataFrame(orders)

# Split list into rows
df = df.explode('items')

# Convert dictionary into columns
items_df = pd.json_normalize(df['items'])

# Combine both
orders_data = pd.concat(
    [df.drop(columns=['items']).reset_index(drop=True),
     items_df.reset_index(drop=True)],
    axis=1
)

print(orders_data.head())

   order_id  user_id  total_price      status  product_id  quantity
0         1        1       849.97     Shipped           1         2
1         1        1       849.97     Shipped           3         1
2         2        2      1149.98   Delivered           2         1
3         2        2      1149.98   Delivered           7         1
4         3        3       599.98  Processing           4         1

## Users Data

In [34]:
# Convert to dataframe
users_data = pd.DataFrame(users)

In [35]:
users_data

   user_id       username              email         password
0        1       john_doe   john@example.com  hashed_password
1        2     jane_smith   jane@example.com  hashed_password
2        3    bob_johnson    bob@example.com  hashed_password
3        4   susan_wilson  susan@example.com  hashed_password
4        5  mike_anderson   mike@example.com  hashed_password

## Products Data

In [36]:
# Convert to dataframe
df = pd.DataFrame(products)

# Split list into rows
df = df.explode('reviews')

# Convert dictionary into columns
items_df = pd.json_normalize(df['reviews'])

# Combine both
product_data = pd.concat(
    [df.drop(columns=['reviews']).reset_index(drop=True),
     items_df.reset_index(drop=True)],
    axis=1
)
print(product_data.head())

   product_id                 name  \
0           1           Smartphone
1           1           Smartphone
2           2               Laptop
3           2               Laptop
4           3  Wireless Headphones

                                         description   price   unit  \
0        High-end smartphone with advanced features.  599.99  Piece
1        High-end smartphone with advanced features.  599.99  Piece
2               Powerful laptop for work and gaming.  999.99  Piece
3               Powerful laptop for work and gaming.  999.99  Piece
4  Premium wireless headphones with noise-cancell...  149.99  Piece

                                       image  discount  availability  \
0  https://example.com/images/smartphone.jpg        10          True
1  https://example.com/images/smartphone.jpg        10          True
2      https://example.com/images/laptop.jpg         5          True
3      https://example.com/images/laptop.jpg         5          True
4  https://example.com/images/headphones.jpg        15          True

          brand     category  rating  user_id  rating  \
0        BrandX  Electronics     4.5      1.0     5.0
1        BrandX  Electronics     4.5      2.0     4.0
2        BrandY  Electronics     4.7      3.0     5.0
3        BrandY  Electronics     4.7      4.0     4.0
4  SoundMasters  Electronics     4.8      5.0     5.0

                                             comment
0                  Great phone with a superb camera!
1  Good performance, but the battery life could b...
2        Excellent laptop for gaming and work tasks.
3                          Good value for the price.
4               Top-notch sound quality and comfort.

In [39]:
orders_data.to_csv('orders.csv', index=False)
users_data.to_csv('users.csv', index=False)
product_data.to_csv('product.csv', index=False)

### Loading Save data into notebook

In [41]:
product = pd.read_csv('product.csv')
order = pd.read_csv('orders.csv')
user = pd.read_csv('users.csv')

# Working with product data

In [43]:
product.head()

,product_id,name,description,price,unit,image,discount,availability,brand,category,rating,user_id,rating.1,comment
0,1,Smartphone,High-end smartphone with advanced features.,599.99,Piece,https://example.com/images/smartphone.jpg,10,True,BrandX,Electronics,4.5,1.0,5.0,Great phone with a superb camera!
1,1,Smartphone,High-end smartphone with advanced features.,599.99,Piece,https://example.com/images/smartphone.jpg,10,True,BrandX,Electronics,4.5,2.0,4.0,"Good performance, but the battery life could b..."
2,2,Laptop,Powerful laptop for work and gaming.,999.99,Piece,https://example.com/images/laptop.jpg,5,True,BrandY,Electronics,4.7,3.0,5.0,Excellent laptop for gaming and work tasks.
3,2,Laptop,Powerful laptop for work and gaming.,999.99,Piece,https://example.com/images/laptop.jpg,5,True,BrandY,Electronics,4.7,4.0,4.0,Good value for the price.
4,3,Wireless Headphones,Premium wireless headphones with noise-cancell...,149.99,Piece,https://example.com/images/headphones.jpg,15,True,SoundMasters,Electronics,4.8,5.0,5.0,Top-notch sound quality and comfort.

In [44]:
product.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 17 entries, 0 to 16
Data columns (total 14 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   product_id    17 non-null     int64
 1   name          17 non-null     object
 2   description   17 non-null     object
 3   price         17 non-null     float64
 4   unit          17 non-null     object
 5   image         17 non-null     object
 6   discount      17 non-null     int64
 7   availability  17 non-null     bool
 8   brand         17 non-null     object
 9   category      17 non-null     object
 10  rating        17 non-null     float64
 11  user_id       16 non-null     float64
 12  rating.1      16 non-null     float64
 13  comment       16 non-null     object
dtypes: bool(1), float64(4), int64(2), object(7)
memory usage: 1.9+ KB

In [45]:
product.shape

(17, 14)

In [46]:
product.describe(include="all")

,product_id,name,description,price,unit,image,discount,availability,brand,category,rating,user_id,rating.1,comment
count,17.000000,17,17,17.000000,17,17,17.000000,17,17,17,17.000000,16.000000,16.000000,16
unique,NaN,9,9,NaN,1,9,NaN,1,9,5,NaN,NaN,NaN,16
top,NaN,Smartphone,High-end smartphone with advanced features.,NaN,Piece,https://example.com/images/smartphone.jpg,NaN,True,BrandX,Electronics,NaN,NaN,NaN,Great phone with a superb camera!
freq,NaN,2,2,NaN,17,2,NaN,17,2,10,NaN,NaN,NaN,1
mean,4.764706,NaN,NaN,499.990000,NaN,NaN,9.117647,NaN,NaN,NaN,4.670588,8.500000,4.500000,NaN
std,2.537947,NaN,NaN,277.826385,NaN,NaN,3.333211,NaN,NaN,NaN,0.157181,4.760952,0.516398,NaN
min,1.000000,NaN,NaN,149.990000,NaN,NaN,5.000000,NaN,NaN,NaN,4.400000,1.000000,4.000000,NaN
25%,3.000000,NaN,NaN,299.990000,NaN,NaN,5.000000,NaN,NaN,NaN,4.600000,4.750000,4.000000,NaN
50%,5.000000,NaN,NaN,499.990000,NaN,NaN,10.000000,NaN,NaN,NaN,4.700000,8.500000,4.500000,NaN
75%,7.000000,NaN,NaN,599.990000,NaN,NaN,10.000000,NaN,NaN,NaN,4.800000,12.250000,5.000000,NaN
max,9.000000,NaN,NaN,999.990000,NaN,NaN,15.000000,NaN,NaN,NaN,4.900000,16.000000,5.000000,NaN

In [47]:
product.isnull().sum()

product_id      0
name            0
description     0
price           0
unit            0
image           0
discount        0
availability    0
brand           0
category        0
rating          0
user_id         1
rating.1        1
comment         1
dtype: int64

In [48]:
product.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 17 entries, 0 to 16
Data columns (total 14 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   product_id    17 non-null     int64
 1   name          17 non-null     object
 2   description   17 non-null     object
 3   price         17 non-null     float64
 4   unit          17 non-null     object
 5   image         17 non-null     object
 6   discount      17 non-null     int64
 7   availability  17 non-null     bool
 8   brand         17 non-null     object
 9   category      17 non-null     object
 10  rating        17 non-null     float64
 11  user_id       16 non-null     float64
 12  rating.1      16 non-null     float64
 13  comment       16 non-null     object
dtypes: bool(1), float64(4), int64(2), object(7)
memory usage: 1.9+ KB

### Performing groupby

In [52]:
product_with_max_Price = product.groupby("name", as_index=False)['price'].max()

In [53]:
product_with_max_Price

                            name   price
0  Energy-Efficient Refrigerator  599.99
1                 Gaming Console  399.99
2                         Laptop  999.99
3       Professional DSLR Camera  499.99
4                       Smart TV  799.99
5                     Smartphone  599.99
6                     Smartwatch  199.99
7                         Tablet  299.99
8            Wireless Headphones  149.99

In [56]:
product.groupby(['name', "rating", "price"], as_index=False)['price'].max()

                            name  rating   price
0  Energy-Efficient Refrigerator     4.6  599.99
1                 Gaming Console     4.8  399.99
2                         Laptop     4.7  999.99
3       Professional DSLR Camera     4.9  499.99
4                       Smart TV     4.7  799.99
5                     Smartphone     4.5  599.99
6                     Smartwatch     4.6  199.99
7                         Tablet     4.4  299.99
8            Wireless Headphones     4.8  149.99

In [57]:
product.groupby(['name', "rating", "price"], as_index=False)['price'].agg(["min", "max", "mean", "sum", "count"])

,name,rating,price,min,max,mean,sum,count
0,Energy-Efficient Refrigerator,4.6,599.99,599.99,599.99,599.99,599.99,1
1,Gaming Console,4.8,399.99,399.99,399.99,399.99,799.98,2
2,Laptop,4.7,999.99,999.99,999.99,999.99,1999.98,2
3,Professional DSLR Camera,4.9,499.99,499.99,499.99,499.99,999.98,2
4,Smart TV,4.7,799.99,799.99,799.99,799.99,1599.98,2
5,Smartphone,4.5,599.99,599.99,599.99,599.99,1199.98,2
6,Smartwatch,4.6,199.99,199.99,199.99,199.99,399.98,2
7,Tablet,4.4,299.99,299.99,299.99,299.99,599.98,2
8,Wireless Headphones,4.8,149.99,149.99,149.99,149.99,299.98,2

# Joins performing on order and user table

### inner

In [62]:
order_user_inner = pd.merge(
    order,
    product,
    on="user_id",
    how="inner"
)

print(order_user_inner)

   order_id  user_id  total_price      status  product_id_x  quantity  \
0         1        1       849.97     Shipped             1         2
1         1        1       849.97     Shipped             3         1
2         2        2      1149.98   Delivered             2         1
3         2        2      1149.98   Delivered             7         1
4         3        3       599.98  Processing             4         1
5         3        3       599.98  Processing             8         1
6         4        4      1099.97     Shipped             5         1
7         4        4      1099.97     Shipped            10         2
8         5        5      1399.98   Delivered             6         1
9         5        5      1399.98   Delivered             9         1

   product_id_y                 name  \
0             1           Smartphone
1             1           Smartphone
2             1           Smartphone
3             1           Smartphone
4             2               Laptop
5             2               Laptop
6             2               Laptop
7             2               Laptop
8             3  Wireless Headphones
9             3  Wireless Headphones

                                         description   price   unit  \
0        High-end smartphone with advanced features.  599.99  Piece
1        High-end smartphone with advanced features.  599.99  Piece
2        High-end smartphone with advanced features.  599.99  Piece
3        High-end smartphone with advanced features.  599.99  Piece
4               Powerful laptop for work and gaming.  999.99  Piece
5               Powerful laptop for work and gaming.  999.99  Piece
6               Powerful laptop for work and gaming.  999.99  Piece
7               Powerful laptop for work and gaming.  999.99  Piece
8  Premium wireless headphones with noise-cancell...  149.99  Piece
9  Premium wireless headphones with noise-cancell...  149.99  Piece

                                       image  discount  availability  \
0  https://example.com/images/smartphone.jpg        10          True
1  https://example.com/images/smartphone.jpg        10          True
2  https://example.com/images/smartphone.jpg        10          True
3  https://example.com/images/smartphone.jpg        10          True
4      https://example.com/images/laptop.jpg         5          True
5      https://example.com/images/laptop.jpg         5          True
6      https://example.com/images/laptop.jpg         5          True
7      https://example.com/images/laptop.jpg         5          True
8  https://example.com/images/headphones.jpg        15          True
9  https://example.com/images/headphones.jpg        15          True

          brand     category  rating  rating.1  \
0        BrandX  Electronics     4.5       5.0
1        BrandX  Electronics     4.5       5.0
2        BrandX  Electronics     4.5       4.0
3        BrandX  Electronics     4.5       4.0
4        BrandY  Electronics     4.7       5.0
5        BrandY  Electronics     4.7       5.0
6        BrandY  Electronics     4.7       4.0
7        BrandY  Electronics     4.7       4.0
8  SoundMasters  Electronics     4.8       5.0
9  SoundMasters  Electronics     4.8       5.0

                                             comment
0                  Great phone with a superb camera!
1                  Great phone with a superb camera!
2  Good performance, but the battery life could b...
3  Good performance, but the battery life could b...
4        Excellent laptop for gaming and work tasks.
5        Excellent laptop for gaming and work tasks.
6                          Good value for the price.
7                          Good value for the price.
8               Top-notch sound quality and comfort.
9               Top-notch sound quality and comfort.

### left

In [65]:
order_user_left = pd.merge(
    order,
    product,
    on="user_id",
    how="left"
)

print(order_user_left)

   order_id  user_id  total_price      status  product_id_x  quantity  \
0         1        1       849.97     Shipped             1         2
1         1        1       849.97     Shipped             3         1
2         2        2      1149.98   Delivered             2         1
3         2        2      1149.98   Delivered             7         1
4         3        3       599.98  Processing             4         1
5         3        3       599.98  Processing             8         1
6         4        4      1099.97     Shipped             5         1
7         4        4      1099.97     Shipped            10         2
8         5        5      1399.98   Delivered             6         1
9         5        5      1399.98   Delivered             9         1

   product_id_y                 name  \
0             1           Smartphone
1             1           Smartphone
2             1           Smartphone
3             1           Smartphone
4             2               Laptop
5             2               Laptop
6             2               Laptop
7             2               Laptop
8             3  Wireless Headphones
9             3  Wireless Headphones

                                         description   price   unit  \
0        High-end smartphone with advanced features.  599.99  Piece
1        High-end smartphone with advanced features.  599.99  Piece
2        High-end smartphone with advanced features.  599.99  Piece
3        High-end smartphone with advanced features.  599.99  Piece
4               Powerful laptop for work and gaming.  999.99  Piece
5               Powerful laptop for work and gaming.  999.99  Piece
6               Powerful laptop for work and gaming.  999.99  Piece
7               Powerful laptop for work and gaming.  999.99  Piece
8  Premium wireless headphones with noise-cancell...  149.99  Piece
9  Premium wireless headphones with noise-cancell...  149.99  Piece

                                       image  discount  availability  \
0  https://example.com/images/smartphone.jpg        10          True
1  https://example.com/images/smartphone.jpg        10          True
2  https://example.com/images/smartphone.jpg        10          True
3  https://example.com/images/smartphone.jpg        10          True
4      https://example.com/images/laptop.jpg         5          True
5      https://example.com/images/laptop.jpg         5          True
6      https://example.com/images/laptop.jpg         5          True
7      https://example.com/images/laptop.jpg         5          True
8  https://example.com/images/headphones.jpg        15          True
9  https://example.com/images/headphones.jpg        15          True

          brand     category  rating  rating.1  \
0        BrandX  Electronics     4.5       5.0
1        BrandX  Electronics     4.5       5.0
2        BrandX  Electronics     4.5       4.0
3        BrandX  Electronics     4.5       4.0
4        BrandY  Electronics     4.7       5.0
5        BrandY  Electronics     4.7       5.0
6        BrandY  Electronics     4.7       4.0
7        BrandY  Electronics     4.7       4.0
8  SoundMasters  Electronics     4.8       5.0
9  SoundMasters  Electronics     4.8       5.0

                                             comment
0                  Great phone with a superb camera!
1                  Great phone with a superb camera!
2  Good performance, but the battery life could b...
3  Good performance, but the battery life could b...
4        Excellent laptop for gaming and work tasks.
5        Excellent laptop for gaming and work tasks.
6                          Good value for the price.
7                          Good value for the price.
8               Top-notch sound quality and comfort.
9               Top-notch sound quality and comfort.

### right

In [64]:
order_user_right = pd.merge(
    order,
    product,
    on="user_id",
    how="right"
)

print(order_user_right)

    order_id  user_id  total_price      status  product_id_x  quantity  \
0        1.0      1.0       849.97     Shipped           1.0       2.0
1        1.0      1.0       849.97     Shipped           3.0       1.0
2        2.0      2.0      1149.98   Delivered           2.0       1.0
3        2.0      2.0      1149.98   Delivered           7.0       1.0
4        3.0      3.0       599.98  Processing           4.0       1.0
5        3.0      3.0       599.98  Processing           8.0       1.0
6        4.0      4.0      1099.97     Shipped           5.0       1.0
7        4.0      4.0      1099.97     Shipped          10.0       2.0
8        5.0      5.0      1399.98   Delivered           6.0       1.0
9        5.0      5.0      1399.98   Delivered           9.0       1.0
10       NaN      6.0          NaN         NaN           NaN       NaN
11       NaN      7.0          NaN         NaN           NaN       NaN
12       NaN      8.0          NaN         NaN           NaN       NaN
13       NaN      9.0          NaN         NaN           NaN       NaN
14       NaN     10.0          NaN         NaN           NaN       NaN
15       NaN     11.0          NaN         NaN           NaN       NaN
16       NaN     12.0          NaN         NaN           NaN       NaN
17       NaN     13.0          NaN         NaN           NaN       NaN
18       NaN     14.0          NaN         NaN           NaN       NaN
19       NaN     15.0          NaN         NaN           NaN       NaN
20       NaN     16.0          NaN         NaN           NaN       NaN
21       NaN      NaN          NaN         NaN           NaN       NaN

    product_id_y                           name  \
0              1                     Smartphone
1              1                     Smartphone
2              1                     Smartphone
3              1                     Smartphone
4              2                         Laptop
5              2                         Laptop
6              2                         Laptop
7              2                         Laptop
8              3            Wireless Headphones
9              3            Wireless Headphones
10             3            Wireless Headphones
11             4                     Smartwatch
12             4                     Smartwatch
13             5       Professional DSLR Camera
14             5       Professional DSLR Camera
15             6                       Smart TV
16             6                       Smart TV
17             7                         Tablet
18             7                         Tablet
19             8                 Gaming Console
20             8                 Gaming Console
21             9  Energy-Efficient Refrigerator

                                          description   price   unit  \
0         High-end smartphone with advanced features.  599.99  Piece
1         High-end smartphone with advanced features.  599.99  Piece
2         High-end smartphone with advanced features.  599.99  Piece
3         High-end smartphone with advanced features.  599.99  Piece
4                Powerful laptop for work and gaming.  999.99  Piece
5                Powerful laptop for work and gaming.  999.99  Piece
6                Powerful laptop for work and gaming.  999.99  Piece
7                Powerful laptop for work and gaming.  999.99  Piece
8   Premium wireless headphones with noise-cancell...  149.99  Piece
9   Premium wireless headphones with noise-cancell...  149.99  Piece
10  Premium wireless headphones with noise-cancell...  149.99  Piece
11   Feature-packed smartwatch with fitness tracking.  199.99  Piece
12   Feature-packed smartwatch with fitness tracking.  199.99  Piece
13  High-quality DSLR camera for photography enthu...  499.99  Piece
14  High-quality DSLR camera for photography enthu...  499.99  Piece
15  High-definition smart TV with built-in streami...  799.99  Piece
16  High-definition smart TV with built-in streami...  799.99  Piece
17  Compact tablet for productivity and entertainm...  299.99  Piece
18  Compact tablet for productivity and entertainm...  299.99  Piece
19  Next-gen gaming console for immersive gaming e...  399.99  Piece
20  Next-gen gaming console for immersive gaming e...  399.99  Piece
21   Modern refrigerator with energy-saving features.  599.99  Piece

                                          image  discount  availability  \
0     https://example.com/images/smartphone.jpg        10          True
1     https://example.com/images/smartphone.jpg        10          True
2     https://example.com/images/smartphone.jpg        10          True
3     https://example.com/images/smartphone.jpg        10          True
4         https://example.com/images/laptop.jpg         5          True
5         https://example.com/images/laptop.jpg         5          True
6         https://example.com/images/laptop.jpg         5          True
7         https://example.com/images/laptop.jpg         5          True
8     https://example.com/images/headphones.jpg        15          True
9     https://example.com/images/headphones.jpg        15          True
10    https://example.com/images/headphones.jpg        15          True
11    https://example.com/images/smartwatch.jpg        10          True
12    https://example.com/images/smartwatch.jpg        10          True
13        https://example.com/images/camera.jpg         5          True
14        https://example.com/images/camera.jpg         5          True
15            https://example.com/images/tv.jpg         8          True
16            https://example.com/images/tv.jpg         8          True
17        https://example.com/images/tablet.jpg        12          True
18        https://example.com/images/tablet.jpg        12          True
19       https://example.com/images/console.jpg        10          True
20       https://example.com/images/console.jpg        10          True
21  https://example.com/images/refrigerator.jpg         5          True

           brand     category  rating  rating.1  \
0         BrandX  Electronics     4.5       5.0
1         BrandX  Electronics     4.5       5.0
2         BrandX  Electronics     4.5       4.0
3         BrandX  Electronics     4.5       4.0
4         BrandY  Electronics     4.7       5.0
5         BrandY  Electronics     4.7       5.0
6         BrandY  Electronics     4.7       4.0
7         BrandY  Electronics     4.7       4.0
8   SoundMasters  Electronics     4.8       5.0
9   SoundMasters  Electronics     4.8       5.0
10  SoundMasters  Electronics     4.8       4.0
11      TechWear    Wearables     4.6       4.0
12      TechWear    Wearables     4.6       5.0
13      PhotoPro      Cameras     4.9       5.0
14      PhotoPro      Cameras     4.9       4.0
15      ViewTech  Electronics     4.7       5.0
16      ViewTech  Electronics     4.7       4.0
17       TabTech  Electronics     4.4       4.0
18       TabTech  Electronics     4.4       5.0
19         GameX       Gaming     4.8       5.0
20         GameX       Gaming     4.8       4.0
21      CoolTech   Appliances     4.6       NaN

                                              comment
0                   Great phone with a superb camera!
1                   Great phone with a superb camera!
2   Good performance, but the battery life could b...
3   Good performance, but the battery life could b...
4         Excellent laptop for gaming and work tasks.
5         Excellent laptop for gaming and work tasks.
6                           Good value for the price.
7                           Good value for the price.
8                Top-notch sound quality and comfort.
9                Top-notch sound quality and comfort.
10   Impressive noise-cancellation, but a bit pricey.
11            Great value for the features it offers.
12        Sleek design and accurate fitness tracking.
13         Exceptional image quality and versatility.
14         A bit heavy, but the results are worth it.
15  Stunning picture quality and user-friendly int...
16  A great addition to our home entertainment setup.
17  Good value for the price, but the battery life...
18   Ideal for both work and entertainment on the go.
19        Incredible gaming performance and graphics.
20                A must-have for gaming enthusiasts.
21                                                NaN

### outer

In [66]:
order_user_outer = pd.merge(
    order,
    product,
    on="user_id",
    how="outer"
)

print(order_user_outer)

    order_id  user_id  total_price      status  product_id_x  quantity  \
0        1.0      1.0       849.97     Shipped           1.0       2.0
1        1.0      1.0       849.97     Shipped           3.0       1.0
2        2.0      2.0      1149.98   Delivered           2.0       1.0
3        2.0      2.0      1149.98   Delivered           7.0       1.0
4        3.0      3.0       599.98  Processing           4.0       1.0
5        3.0      3.0       599.98  Processing           8.0       1.0
6        4.0      4.0      1099.97     Shipped           5.0       1.0
7        4.0      4.0      1099.97     Shipped          10.0       2.0
8        5.0      5.0      1399.98   Delivered           6.0       1.0
9        5.0      5.0      1399.98   Delivered           9.0       1.0
10       NaN      6.0          NaN         NaN           NaN       NaN
11       NaN      7.0          NaN         NaN           NaN       NaN
12       NaN      8.0          NaN         NaN           NaN       NaN
13       NaN      9.0          NaN         NaN           NaN       NaN
14       NaN     10.0          NaN         NaN           NaN       NaN
15       NaN     11.0          NaN         NaN           NaN       NaN
16       NaN     12.0          NaN         NaN           NaN       NaN
17       NaN     13.0          NaN         NaN           NaN       NaN
18       NaN     14.0          NaN         NaN           NaN       NaN
19       NaN     15.0          NaN         NaN           NaN       NaN
20       NaN     16.0          NaN         NaN           NaN       NaN
21       NaN      NaN          NaN         NaN           NaN       NaN

    product_id_y                           name  \
0              1                     Smartphone
1              1                     Smartphone
2              1                     Smartphone
3              1                     Smartphone
4              2                         Laptop
5              2                         Laptop
6              2                         Laptop
7              2                         Laptop
8              3            Wireless Headphones
9              3            Wireless Headphones
10             3            Wireless Headphones
11             4                     Smartwatch
12             4                     Smartwatch
13             5       Professional DSLR Camera
14             5       Professional DSLR Camera
15             6                       Smart TV
16             6                       Smart TV
17             7                         Tablet
18             7                         Tablet
19             8                 Gaming Console
20             8                 Gaming Console
21             9  Energy-Efficient Refrigerator

                                          description   price   unit  \
0         High-end smartphone with advanced features.  599.99  Piece
1         High-end smartphone with advanced features.  599.99  Piece
2         High-end smartphone with advanced features.  599.99  Piece
3         High-end smartphone with advanced features.  599.99  Piece
4                Powerful laptop for work and gaming.  999.99  Piece
5                Powerful laptop for work and gaming.  999.99  Piece
6                Powerful laptop for work and gaming.  999.99  Piece
7                Powerful laptop for work and gaming.  999.99  Piece
8   Premium wireless headphones with noise-cancell...  149.99  Piece
9   Premium wireless headphones with noise-cancell...  149.99  Piece
10  Premium wireless headphones with noise-cancell...  149.99  Piece
11   Feature-packed smartwatch with fitness tracking.  199.99  Piece
12   Feature-packed smartwatch with fitness tracking.  199.99  Piece
13  High-quality DSLR camera for photography enthu...  499.99  Piece
14  High-quality DSLR camera for photography enthu...  499.99  Piece
15  High-definition smart TV with built-in streami...  799.99  Piece
16  High-definition smart TV with built-in streami...  799.99  Piece
17  Compact tablet for productivity and entertainm...  299.99  Piece
18  Compact tablet for productivity and entertainm...  299.99  Piece
19  Next-gen gaming console for immersive gaming e...  399.99  Piece
20  Next-gen gaming console for immersive gaming e...  399.99  Piece
21   Modern refrigerator with energy-saving features.  599.99  Piece

                                          image  discount  availability  \
0     https://example.com/images/smartphone.jpg        10          True
1     https://example.com/images/smartphone.jpg        10          True
2     https://example.com/images/smartphone.jpg        10          True
3     https://example.com/images/smartphone.jpg        10          True
4         https://example.com/images/laptop.jpg         5          True
5         https://example.com/images/laptop.jpg         5          True
6         https://example.com/images/laptop.jpg         5          True
7         https://example.com/images/laptop.jpg         5          True
8     https://example.com/images/headphones.jpg        15          True
9     https://example.com/images/headphones.jpg        15          True
10    https://example.com/images/headphones.jpg        15          True
11    https://example.com/images/smartwatch.jpg        10          True
12    https://example.com/images/smartwatch.jpg        10          True
13        https://example.com/images/camera.jpg         5          True
14        https://example.com/images/camera.jpg         5          True
15            https://example.com/images/tv.jpg         8          True
16            https://example.com/images/tv.jpg         8          True
17        https://example.com/images/tablet.jpg        12          True
18        https://example.com/images/tablet.jpg        12          True
19       https://example.com/images/console.jpg        10          True
20       https://example.com/images/console.jpg        10          True
21  https://example.com/images/refrigerator.jpg         5          True

           brand     category  rating  rating.1  \
0         BrandX  Electronics     4.5       5.0
1         BrandX  Electronics     4.5       5.0
2         BrandX  Electronics     4.5       4.0
3         BrandX  Electronics     4.5       4.0
4         BrandY  Electronics     4.7       5.0
5         BrandY  Electronics     4.7       5.0
6         BrandY  Electronics     4.7       4.0
7         BrandY  Electronics     4.7       4.0
8   SoundMasters  Electronics     4.8       5.0
9   SoundMasters  Electronics     4.8       5.0
10  SoundMasters  Electronics     4.8       4.0
11      TechWear    Wearables     4.6       4.0
12      TechWear    Wearables     4.6       5.0
13      PhotoPro      Cameras     4.9       5.0
14      PhotoPro      Cameras     4.9       4.0
15      ViewTech  Electronics     4.7       5.0
16      ViewTech  Electronics     4.7       4.0
17       TabTech  Electronics     4.4       4.0
18       TabTech  Electronics     4.4       5.0
19         GameX       Gaming     4.8       5.0
20         GameX       Gaming     4.8       4.0
21      CoolTech   Appliances     4.6       NaN

                                              comment
0                   Great phone with a superb camera!
1                   Great phone with a superb camera!
2   Good performance, but the battery life could b...
3   Good performance, but the battery life could b...
4         Excellent laptop for gaming and work tasks.
5         Excellent laptop for gaming and work tasks.
6                           Good value for the price.
7                           Good value for the price.
8                Top-notch sound quality and comfort.
9                Top-notch sound quality and comfort.
10   Impressive noise-cancellation, but a bit pricey.
11            Great value for the features it offers.
12        Sleek design and accurate fitness tracking.
13         Exceptional image quality and versatility.
14         A bit heavy, but the results are worth it.
15  Stunning picture quality and user-friendly int...
16  A great addition to our home entertainment setup.
17  Good value for the price, but the battery life...
18   Ideal for both work and entertainment on the go.
19        Incredible gaming performance and graphics.
20                A must-have for gaming enthusiasts.
21                                                NaN

### Join Indicator

In [67]:
order_user_outer = pd.merge(
    order,
    product,
    on="user_id",
    how="outer",
    indicator=True
)

print(order_user_outer)

    order_id  user_id  total_price      status  product_id_x  quantity  \
0        1.0      1.0       849.97     Shipped           1.0       2.0
1        1.0      1.0       849.97     Shipped           3.0       1.0
2        2.0      2.0      1149.98   Delivered           2.0       1.0
3        2.0      2.0      1149.98   Delivered           7.0       1.0
4        3.0      3.0       599.98  Processing           4.0       1.0
5        3.0      3.0       599.98  Processing           8.0       1.0
6        4.0      4.0      1099.97     Shipped           5.0       1.0
7        4.0      4.0      1099.97     Shipped          10.0       2.0
8        5.0      5.0      1399.98   Delivered           6.0       1.0
9        5.0      5.0      1399.98   Delivered           9.0       1.0
10       NaN      6.0          NaN         NaN           NaN       NaN
11       NaN      7.0          NaN         NaN           NaN       NaN
12       NaN      8.0          NaN         NaN           NaN       NaN
13       NaN      9.0          NaN         NaN           NaN       NaN
14       NaN     10.0          NaN         NaN           NaN       NaN
15       NaN     11.0          NaN         NaN           NaN       NaN
16       NaN     12.0          NaN         NaN           NaN       NaN
17       NaN     13.0          NaN         NaN           NaN       NaN
18       NaN     14.0          NaN         NaN           NaN       NaN
19       NaN     15.0          NaN         NaN           NaN       NaN
20       NaN     16.0          NaN         NaN           NaN       NaN
21       NaN      NaN          NaN         NaN           NaN       NaN

    product_id_y                           name  \
0              1                     Smartphone
1              1                     Smartphone
2              1                     Smartphone
3              1                     Smartphone
4              2                         Laptop
5              2                         Laptop
6              2                         Laptop
7              2                         Laptop
8              3            Wireless Headphones
9              3            Wireless Headphones
10             3            Wireless Headphones
11             4                     Smartwatch
12             4                     Smartwatch
13             5       Professional DSLR Camera
14             5       Professional DSLR Camera
15             6                       Smart TV
16             6                       Smart TV
17             7                         Tablet
18             7                         Tablet
19             8                 Gaming Console
20             8                 Gaming Console
21             9  Energy-Efficient Refrigerator

                                          description   price   unit  \
0         High-end smartphone with advanced features.  599.99  Piece
1         High-end smartphone with advanced features.  599.99  Piece
2         High-end smartphone with advanced features.  599.99  Piece
3         High-end smartphone with advanced features.  599.99  Piece
4                Powerful laptop for work and gaming.  999.99  Piece
5                Powerful laptop for work and gaming.  999.99  Piece
6                Powerful laptop for work and gaming.  999.99  Piece
7                Powerful laptop for work and gaming.  999.99  Piece
8   Premium wireless headphones with noise-cancell...  149.99  Piece
9   Premium wireless headphones with noise-cancell...  149.99  Piece
10  Premium wireless headphones with noise-cancell...  149.99  Piece
11   Feature-packed smartwatch with fitness tracking.  199.99  Piece
12   Feature-packed smartwatch with fitness tracking.  199.99  Piece
13  High-quality DSLR camera for photography enthu...  499.99  Piece
14  High-quality DSLR camera for photography enthu...  499.99  Piece
15  High-definition smart TV with built-in streami...  799.99  Piece
16  High-definition smart TV with built-in streami...  799.99  Piece
17  Compact tablet for productivity and entertainm...  299.99  Piece
18  Compact tablet for productivity and entertainm...  299.99  Piece
19  Next-gen gaming console for immersive gaming e...  399.99  Piece
20  Next-gen gaming console for immersive gaming e...  399.99  Piece
21   Modern refrigerator with energy-saving features.  599.99  Piece

                                          image  discount  availability  \
0     https://example.com/images/smartphone.jpg        10          True
1     https://example.com/images/smartphone.jpg        10          True
2     https://example.com/images/smartphone.jpg        10          True
3     https://example.com/images/smartphone.jpg        10          True
4         https://example.com/images/laptop.jpg         5          True
5         https://example.com/images/laptop.jpg         5          True
6         https://example.com/images/laptop.jpg         5          True
7         https://example.com/images/laptop.jpg         5          True
8     https://example.com/images/headphones.jpg        15          True
9     https://example.com/images/headphones.jpg        15          True
10    https://example.com/images/headphones.jpg        15          True
11    https://example.com/images/smartwatch.jpg        10          True
12    https://example.com/images/smartwatch.jpg        10          True
13        https://example.com/images/camera.jpg         5          True
14        https://example.com/images/camera.jpg         5          True
15            https://example.com/images/tv.jpg         8          True
16            https://example.com/images/tv.jpg         8          True
17        https://example.com/images/tablet.jpg        12          True
18        https://example.com/images/tablet.jpg        12          True
19       https://example.com/images/console.jpg        10          True
20       https://example.com/images/console.jpg        10          True
21  https://example.com/images/refrigerator.jpg         5          True

           brand     category  rating  rating.1  \
0         BrandX  Electronics     4.5       5.0
1         BrandX  Electronics     4.5       5.0
2         BrandX  Electronics     4.5       4.0
3         BrandX  Electronics     4.5       4.0
4         BrandY  Electronics     4.7       5.0
5         BrandY  Electronics     4.7       5.0
6         BrandY  Electronics     4.7       4.0
7         BrandY  Electronics     4.7       4.0
8   SoundMasters  Electronics     4.8       5.0
9   SoundMasters  Electronics     4.8       5.0
10  SoundMasters  Electronics     4.8       4.0
11      TechWear    Wearables     4.6       4.0
12      TechWear    Wearables     4.6       5.0
13      PhotoPro      Cameras     4.9       5.0
14      PhotoPro      Cameras     4.9       4.0
15      ViewTech  Electronics     4.7       5.0
16      ViewTech  Electronics     4.7       4.0
17       TabTech  Electronics     4.4       4.0
18       TabTech  Electronics     4.4       5.0
19         GameX       Gaming     4.8       5.0
20         GameX       Gaming     4.8       4.0
21      CoolTech   Appliances     4.6       NaN

                                              comment      _merge
0                   Great phone with a superb camera!        both
1                   Great phone with a superb camera!        both
2   Good performance, but the battery life could b...        both
3   Good performance, but the battery life could b...        both
4         Excellent laptop for gaming and work tasks.        both
5         Excellent laptop for gaming and work tasks.        both
6                           Good value for the price.        both
7                           Good value for the price.        both
8                Top-notch sound quality and comfort.        both
9                Top-notch sound quality and comfort.        both
10   Impressive noise-cancellation, but a bit pricey.  right_only
11            Great value for the features it offers.  right_only
12        Sleek design and accurate fitness tracking.  right_only
13         Exceptional image quality and versatility.  right_only
14         A bit heavy, but the results are worth it.  right_only
15  Stunning picture quality and user-friendly int...  right_only
16  A great addition to our home entertainment setup.  right_only
17  Good value for the price, but the battery life...  right_only
18   Ideal for both work and entertainment on the go.  right_only
19        Incredible gaming performance and graphics.  right_only
20                A must-have for gaming enthusiasts.  right_only
21                                                NaN  right_only

# Joins performing on order and product table

### inner

In [69]:
order_product_inner = pd.merge(
    order,
    product,
    on="user_id",
    how="inner"
)

print(order_product_inner)

   order_id  user_id  total_price      status  product_id_x  quantity  \
0         1        1       849.97     Shipped             1         2
1         1        1       849.97     Shipped             3         1
2         2        2      1149.98   Delivered             2         1
3         2        2      1149.98   Delivered             7         1
4         3        3       599.98  Processing             4         1
5         3        3       599.98  Processing             8         1
6         4        4      1099.97     Shipped             5         1
7         4        4      1099.97     Shipped            10         2
8         5        5      1399.98   Delivered             6         1
9         5        5      1399.98   Delivered             9         1

   product_id_y                 name  \
0             1           Smartphone
1             1           Smartphone
2             1           Smartphone
3             1           Smartphone
4             2               Laptop
5             2               Laptop
6             2               Laptop
7             2               Laptop
8             3  Wireless Headphones
9             3  Wireless Headphones

                                         description   price   unit  \
0        High-end smartphone with advanced features.  599.99  Piece
1        High-end smartphone with advanced features.  599.99  Piece
2        High-end smartphone with advanced features.  599.99  Piece
3        High-end smartphone with advanced features.  599.99  Piece
4               Powerful laptop for work and gaming.  999.99  Piece
5               Powerful laptop for work and gaming.  999.99  Piece
6               Powerful laptop for work and gaming.  999.99  Piece
7               Powerful laptop for work and gaming.  999.99  Piece
8  Premium wireless headphones with noise-cancell...  149.99  Piece
9  Premium wireless headphones with noise-cancell...  149.99  Piece

                                       image  discount  availability  \
0  https://example.com/images/smartphone.jpg        10          True
1  https://example.com/images/smartphone.jpg        10          True
2  https://example.com/images/smartphone.jpg        10          True
3  https://example.com/images/smartphone.jpg        10          True
4      https://example.com/images/laptop.jpg         5          True
5      https://example.com/images/laptop.jpg         5          True
6      https://example.com/images/laptop.jpg         5          True
7      https://example.com/images/laptop.jpg         5          True
8  https://example.com/images/headphones.jpg        15          True
9  https://example.com/images/headphones.jpg        15          True

          brand     category  rating  rating.1  \
0        BrandX  Electronics     4.5       5.0
1        BrandX  Electronics     4.5       5.0
2        BrandX  Electronics     4.5       4.0
3        BrandX  Electronics     4.5       4.0
4        BrandY  Electronics     4.7       5.0
5        BrandY  Electronics     4.7       5.0
6        BrandY  Electronics     4.7       4.0
7        BrandY  Electronics     4.7       4.0
8  SoundMasters  Electronics     4.8       5.0
9  SoundMasters  Electronics     4.8       5.0

                                             comment
0                  Great phone with a superb camera!
1                  Great phone with a superb camera!
2  Good performance, but the battery life could b...
3  Good performance, but the battery life could b...
4        Excellent laptop for gaming and work tasks.
5        Excellent laptop for gaming and work tasks.
6                          Good value for the price.
7                          Good value for the price.
8               Top-notch sound quality and comfort.
9               Top-notch sound quality and comfort.

### left

In [70]:
order_product_left = pd.merge(
    order,
    product,
    on="user_id",
    how="left"
)

print(order_product_left)

   order_id  user_id  total_price      status  product_id_x  quantity  \
0         1        1       849.97     Shipped             1         2
1         1        1       849.97     Shipped             3         1
2         2        2      1149.98   Delivered             2         1
3         2        2      1149.98   Delivered             7         1
4         3        3       599.98  Processing             4         1
5         3        3       599.98  Processing             8         1
6         4        4      1099.97     Shipped             5         1
7         4        4      1099.97     Shipped            10         2
8         5        5      1399.98   Delivered             6         1
9         5        5      1399.98   Delivered             9         1

   product_id_y                 name  \
0             1           Smartphone
1             1           Smartphone
2             1           Smartphone
3             1           Smartphone
4             2               Laptop
5             2               Laptop
6             2               Laptop
7             2               Laptop
8             3  Wireless Headphones
9             3  Wireless Headphones

                                         description   price   unit  \
0        High-end smartphone with advanced features.  599.99  Piece
1        High-end smartphone with advanced features.  599.99  Piece
2        High-end smartphone with advanced features.  599.99  Piece
3        High-end smartphone with advanced features.  599.99  Piece
4               Powerful laptop for work and gaming.  999.99  Piece
5               Powerful laptop for work and gaming.  999.99  Piece
6               Powerful laptop for work and gaming.  999.99  Piece
7               Powerful laptop for work and gaming.  999.99  Piece
8  Premium wireless headphones with noise-cancell...  149.99  Piece
9  Premium wireless headphones with noise-cancell...  149.99  Piece

                                       image  discount  availability  \
0  https://example.com/images/smartphone.jpg        10          True
1  https://example.com/images/smartphone.jpg        10          True
2  https://example.com/images/smartphone.jpg        10          True
3  https://example.com/images/smartphone.jpg        10          True
4      https://example.com/images/laptop.jpg         5          True
5      https://example.com/images/laptop.jpg         5          True
6      https://example.com/images/laptop.jpg         5          True
7      https://example.com/images/laptop.jpg         5          True
8  https://example.com/images/headphones.jpg        15          True
9  https://example.com/images/headphones.jpg        15          True

          brand     category  rating  rating.1  \
0        BrandX  Electronics     4.5       5.0
1        BrandX  Electronics     4.5       5.0
2        BrandX  Electronics     4.5       4.0
3        BrandX  Electronics     4.5       4.0
4        BrandY  Electronics     4.7       5.0
5        BrandY  Electronics     4.7       5.0
6        BrandY  Electronics     4.7       4.0
7        BrandY  Electronics     4.7       4.0
8  SoundMasters  Electronics     4.8       5.0
9  SoundMasters  Electronics     4.8       5.0

                                             comment
0                  Great phone with a superb camera!
1                  Great phone with a superb camera!
2  Good performance, but the battery life could b...
3  Good performance, but the battery life could b...
4        Excellent laptop for gaming and work tasks.
5        Excellent laptop for gaming and work tasks.
6                          Good value for the price.
7                          Good value for the price.
8               Top-notch sound quality and comfort.
9               Top-notch sound quality and comfort.

### right

In [71]:
order_product_right = pd.merge(
    order,
    product,
    on="user_id",
    how="right"
)

print(order_product_right)

    order_id  user_id  total_price      status  product_id_x  quantity  \
0        1.0      1.0       849.97     Shipped           1.0       2.0
1        1.0      1.0       849.97     Shipped           3.0       1.0
2        2.0      2.0      1149.98   Delivered           2.0       1.0
3        2.0      2.0      1149.98   Delivered           7.0       1.0
4        3.0      3.0       599.98  Processing           4.0       1.0
5        3.0      3.0       599.98  Processing           8.0       1.0
6        4.0      4.0      1099.97     Shipped           5.0       1.0
7        4.0      4.0      1099.97     Shipped          10.0       2.0
8        5.0      5.0      1399.98   Delivered           6.0       1.0
9        5.0      5.0      1399.98   Delivered           9.0       1.0
10       NaN      6.0          NaN         NaN           NaN       NaN
11       NaN      7.0          NaN         NaN           NaN       NaN
12       NaN      8.0          NaN         NaN           NaN       NaN
13       NaN      9.0          NaN         NaN           NaN       NaN
14       NaN     10.0          NaN         NaN           NaN       NaN
15       NaN     11.0          NaN         NaN           NaN       NaN
16       NaN     12.0          NaN         NaN           NaN       NaN
17       NaN     13.0          NaN         NaN           NaN       NaN
18       NaN     14.0          NaN         NaN           NaN       NaN
19       NaN     15.0          NaN         NaN           NaN       NaN
20       NaN     16.0          NaN         NaN           NaN       NaN
21       NaN      NaN          NaN         NaN           NaN       NaN

    product_id_y                           name  \
0              1                     Smartphone
1              1                     Smartphone
2              1                     Smartphone
3              1                     Smartphone
4              2                         Laptop
5              2                         Laptop
6              2                         Laptop
7              2                         Laptop
8              3            Wireless Headphones
9              3            Wireless Headphones
10             3            Wireless Headphones
11             4                     Smartwatch
12             4                     Smartwatch
13             5       Professional DSLR Camera
14             5       Professional DSLR Camera
15             6                       Smart TV
16             6                       Smart TV
17             7                         Tablet
18             7                         Tablet
19             8                 Gaming Console
20             8                 Gaming Console
21             9  Energy-Efficient Refrigerator

                                          description   price   unit  \
0         High-end smartphone with advanced features.  599.99  Piece
1         High-end smartphone with advanced features.  599.99  Piece
2         High-end smartphone with advanced features.  599.99  Piece
3         High-end smartphone with advanced features.  599.99  Piece
4                Powerful laptop for work and gaming.  999.99  Piece
5                Powerful laptop for work and gaming.  999.99  Piece
6                Powerful laptop for work and gaming.  999.99  Piece
7                Powerful laptop for work and gaming.  999.99  Piece
8   Premium wireless headphones with noise-cancell...  149.99  Piece
9   Premium wireless headphones with noise-cancell...  149.99  Piece
10  Premium wireless headphones with noise-cancell...  149.99  Piece
11   Feature-packed smartwatch with fitness tracking.  199.99  Piece
12   Feature-packed smartwatch with fitness tracking.  199.99  Piece
13  High-quality DSLR camera for photography enthu...  499.99  Piece
14  High-quality DSLR camera for photography enthu...  499.99  Piece
15  High-definition smart TV with built-in streami...  799.99  Piece
16  High-definition smart TV with built-in streami...  799.99  Piece
17  Compact tablet for productivity and entertainm...  299.99  Piece
18  Compact tablet for productivity and entertainm...  299.99  Piece
19  Next-gen gaming console for immersive gaming e...  399.99  Piece
20  Next-gen gaming console for immersive gaming e...  399.99  Piece
21   Modern refrigerator with energy-saving features.  599.99  Piece

                                          image  discount  availability  \
0     https://example.com/images/smartphone.jpg        10          True
1     https://example.com/images/smartphone.jpg        10          True
2     https://example.com/images/smartphone.jpg        10          True
3     https://example.com/images/smartphone.jpg        10          True
4         https://example.com/images/laptop.jpg         5          True
5         https://example.com/images/laptop.jpg         5          True
6         https://example.com/images/laptop.jpg         5          True
7         https://example.com/images/laptop.jpg         5          True
8     https://example.com/images/headphones.jpg        15          True
9     https://example.com/images/headphones.jpg        15          True
10    https://example.com/images/headphones.jpg        15          True
11    https://example.com/images/smartwatch.jpg        10          True
12    https://example.com/images/smartwatch.jpg        10          True
13        https://example.com/images/camera.jpg         5          True
14        https://example.com/images/camera.jpg         5          True
15            https://example.com/images/tv.jpg         8          True
16            https://example.com/images/tv.jpg         8          True
17        https://example.com/images/tablet.jpg        12          True
18        https://example.com/images/tablet.jpg        12          True
19       https://example.com/images/console.jpg        10          True
20       https://example.com/images/console.jpg        10          True
21  https://example.com/images/refrigerator.jpg         5          True

           brand     category  rating  rating.1  \
0         BrandX  Electronics     4.5       5.0
1         BrandX  Electronics     4.5       5.0
2         BrandX  Electronics     4.5       4.0
3         BrandX  Electronics     4.5       4.0
4         BrandY  Electronics     4.7       5.0
5         BrandY  Electronics     4.7       5.0
6         BrandY  Electronics     4.7       4.0
7         BrandY  Electronics     4.7       4.0
8   SoundMasters  Electronics     4.8       5.0
9   SoundMasters  Electronics     4.8       5.0
10  SoundMasters  Electronics     4.8       4.0
11      TechWear    Wearables     4.6       4.0
12      TechWear    Wearables     4.6       5.0
13      PhotoPro      Cameras     4.9       5.0
14      PhotoPro      Cameras     4.9       4.0
15      ViewTech  Electronics     4.7       5.0
16      ViewTech  Electronics     4.7       4.0
17       TabTech  Electronics     4.4       4.0
18       TabTech  Electronics     4.4       5.0
19         GameX       Gaming     4.8       5.0
20         GameX       Gaming     4.8       4.0
21      CoolTech   Appliances     4.6       NaN

                                              comment
0                   Great phone with a superb camera!
1                   Great phone with a superb camera!
2   Good performance, but the battery life could b...
3   Good performance, but the battery life could b...
4         Excellent laptop for gaming and work tasks.
5         Excellent laptop for gaming and work tasks.
6                           Good value for the price.
7                           Good value for the price.
8                Top-notch sound quality and comfort.
9                Top-notch sound quality and comfort.
10   Impressive noise-cancellation, but a bit pricey.
11            Great value for the features it offers.
12        Sleek design and accurate fitness tracking.
13         Exceptional image quality and versatility.
14         A bit heavy, but the results are worth it.
15  Stunning picture quality and user-friendly int...
16  A great addition to our home entertainment setup.
17  Good value for the price, but the battery life...
18   Ideal for both work and entertainment on the go.
19        Incredible gaming performance and graphics.
20                A must-have for gaming enthusiasts.
21                                                NaN

### outer

In [72]:
order_product_outer = pd.merge(
    order,
    product,
    on="user_id",
    how="outer"
)

print(order_product_outer)

    order_id  user_id  total_price      status  product_id_x  quantity  \
0        1.0      1.0       849.97     Shipped           1.0       2.0
1        1.0      1.0       849.97     Shipped           3.0       1.0
2        2.0      2.0      1149.98   Delivered           2.0       1.0
3        2.0      2.0      1149.98   Delivered           7.0       1.0
4        3.0      3.0       599.98  Processing           4.0       1.0
5        3.0      3.0       599.98  Processing           8.0       1.0
6        4.0      4.0      1099.97     Shipped           5.0       1.0
7        4.0      4.0      1099.97     Shipped          10.0       2.0
8        5.0      5.0      1399.98   Delivered           6.0       1.0
9        5.0      5.0      1399.98   Delivered           9.0       1.0
10       NaN      6.0          NaN         NaN           NaN       NaN
11       NaN      7.0          NaN         NaN           NaN       NaN
12       NaN      8.0          NaN         NaN           NaN       NaN
13       NaN      9.0          NaN         NaN           NaN       NaN
14       NaN     10.0          NaN         NaN           NaN       NaN
15       NaN     11.0          NaN         NaN           NaN       NaN
16       NaN     12.0          NaN         NaN           NaN       NaN
17       NaN     13.0          NaN         NaN           NaN       NaN
18       NaN     14.0          NaN         NaN           NaN       NaN
19       NaN     15.0          NaN         NaN           NaN       NaN
20       NaN     16.0          NaN         NaN           NaN       NaN
21       NaN      NaN          NaN         NaN           NaN       NaN

    product_id_y                           name  \
0              1                     Smartphone
1              1                     Smartphone
2              1                     Smartphone
3              1                     Smartphone
4              2                         Laptop
5              2                         Laptop
6              2                         Laptop
7              2                         Laptop
8              3            Wireless Headphones
9              3            Wireless Headphones
10             3            Wireless Headphones
11             4                     Smartwatch
12             4                     Smartwatch
13             5       Professional DSLR Camera
14             5       Professional DSLR Camera
15             6                       Smart TV
16             6                       Smart TV
17             7                         Tablet
18             7                         Tablet
19             8                 Gaming Console
20             8                 Gaming Console
21             9  Energy-Efficient Refrigerator

                                          description   price   unit  \
0         High-end smartphone with advanced features.  599.99  Piece
1         High-end smartphone with advanced features.  599.99  Piece
2         High-end smartphone with advanced features.  599.99  Piece
3         High-end smartphone with advanced features.  599.99  Piece
4                Powerful laptop for work and gaming.  999.99  Piece
5                Powerful laptop for work and gaming.  999.99  Piece
6                Powerful laptop for work and gaming.  999.99  Piece
7                Powerful laptop for work and gaming.  999.99  Piece
8   Premium wireless headphones with noise-cancell...  149.99  Piece
9   Premium wireless headphones with noise-cancell...  149.99  Piece
10  Premium wireless headphones with noise-cancell...  149.99  Piece
11   Feature-packed smartwatch with fitness tracking.  199.99  Piece
12   Feature-packed smartwatch with fitness tracking.  199.99  Piece
13  High-quality DSLR camera for photography enthu...  499.99  Piece
14  High-quality DSLR camera for photography enthu...  499.99  Piece
15  High-definition smart TV with built-in streami...  799.99  Piece
16  High-definition smart TV with built-in streami...  799.99  Piece
17  Compact tablet for productivity and entertainm...  299.99  Piece
18  Compact tablet for productivity and entertainm...  299.99  Piece
19  Next-gen gaming console for immersive gaming e...  399.99  Piece
20  Next-gen gaming console for immersive gaming e...  399.99  Piece
21   Modern refrigerator with energy-saving features.  599.99  Piece

                                          image  discount  availability  \
0     https://example.com/images/smartphone.jpg        10          True
1     https://example.com/images/smartphone.jpg        10          True
2     https://example.com/images/smartphone.jpg        10          True
3     https://example.com/images/smartphone.jpg        10          True
4         https://example.com/images/laptop.jpg         5          True
5         https://example.com/images/laptop.jpg         5          True
6         https://example.com/images/laptop.jpg         5          True
7         https://example.com/images/laptop.jpg         5          True
8     https://example.com/images/headphones.jpg        15          True
9     https://example.com/images/headphones.jpg        15          True
10    https://example.com/images/headphones.jpg        15          True
11    https://example.com/images/smartwatch.jpg        10          True
12    https://example.com/images/smartwatch.jpg        10          True
13        https://example.com/images/camera.jpg         5          True
14        https://example.com/images/camera.jpg         5          True
15            https://example.com/images/tv.jpg         8          True
16            https://example.com/images/tv.jpg         8          True
17        https://example.com/images/tablet.jpg        12          True
18        https://example.com/images/tablet.jpg        12          True
19       https://example.com/images/console.jpg        10          True
20       https://example.com/images/console.jpg        10          True
21  https://example.com/images/refrigerator.jpg         5          True

           brand     category  rating  rating.1  \
0         BrandX  Electronics     4.5       5.0
1         BrandX  Electronics     4.5       5.0
2         BrandX  Electronics     4.5       4.0
3         BrandX  Electronics     4.5       4.0
4         BrandY  Electronics     4.7       5.0
5         BrandY  Electronics     4.7       5.0
6         BrandY  Electronics     4.7       4.0
7         BrandY  Electronics     4.7       4.0
8   SoundMasters  Electronics     4.8       5.0
9   SoundMasters  Electronics     4.8       5.0
10  SoundMasters  Electronics     4.8       4.0
11      TechWear    Wearables     4.6       4.0
12      TechWear    Wearables     4.6       5.0
13      PhotoPro      Cameras     4.9       5.0
14      PhotoPro      Cameras     4.9       4.0
15      ViewTech  Electronics     4.7       5.0
16      ViewTech  Electronics     4.7       4.0
17       TabTech  Electronics     4.4       4.0
18       TabTech  Electronics     4.4       5.0
19         GameX       Gaming     4.8       5.0
20         GameX       Gaming     4.8       4.0
21      CoolTech   Appliances     4.6       NaN

                                              comment
0                   Great phone with a superb camera!
1                   Great phone with a superb camera!
2   Good performance, but the battery life could b...
3   Good performance, but the battery life could b...
4         Excellent laptop for gaming and work tasks.
5         Excellent laptop for gaming and work tasks.
6                           Good value for the price.
7                           Good value for the price.
8                Top-notch sound quality and comfort.
9                Top-notch sound quality and comfort.
10   Impressive noise-cancellation, but a bit pricey.
11            Great value for the features it offers.
12        Sleek design and accurate fitness tracking.
13         Exceptional image quality and versatility.
14         A bit heavy, but the results are worth it.
15  Stunning picture quality and user-friendly int...
16  A great addition to our home entertainment setup.
17  Good value for the price, but the battery life...
18   Ideal for both work and entertainment on the go.
19        Incredible gaming performance and graphics.
20                A must-have for gaming enthusiasts.
21                                                NaN

### Join Indicator

In [73]:
from textwrap import indent
order_product_outer = pd.merge(
    order,
    product,
    on="user_id",
    how="outer",
    indicator=True
)

print(order_product_outer)

    order_id  user_id  total_price      status  product_id_x  quantity  \
0        1.0      1.0       849.97     Shipped           1.0       2.0
1        1.0      1.0       849.97     Shipped           3.0       1.0
2        2.0      2.0      1149.98   Delivered           2.0       1.0
3        2.0      2.0      1149.98   Delivered           7.0       1.0
4        3.0      3.0       599.98  Processing           4.0       1.0
5        3.0      3.0       599.98  Processing           8.0       1.0
6        4.0      4.0      1099.97     Shipped           5.0       1.0
7        4.0      4.0      1099.97     Shipped          10.0       2.0
8        5.0      5.0      1399.98   Delivered           6.0       1.0
9        5.0      5.0      1399.98   Delivered           9.0       1.0
10       NaN      6.0          NaN         NaN           NaN       NaN
11       NaN      7.0          NaN         NaN           NaN       NaN
12       NaN      8.0          NaN         NaN           NaN       NaN
13       NaN      9.0          NaN         NaN           NaN       NaN
14       NaN     10.0          NaN         NaN           NaN       NaN
15       NaN     11.0          NaN         NaN           NaN       NaN
16       NaN     12.0          NaN         NaN           NaN       NaN
17       NaN     13.0          NaN         NaN           NaN       NaN
18       NaN     14.0          NaN         NaN           NaN       NaN
19       NaN     15.0          NaN         NaN           NaN       NaN
20       NaN     16.0          NaN         NaN           NaN       NaN
21       NaN      NaN          NaN         NaN           NaN       NaN

    product_id_y                           name  \
0              1                     Smartphone
1              1                     Smartphone
2              1                     Smartphone
3              1                     Smartphone
4              2                         Laptop
5              2                         Laptop
6              2                         Laptop
7              2                         Laptop
8              3            Wireless Headphones
9              3            Wireless Headphones
10             3            Wireless Headphones
11             4                     Smartwatch
12             4                     Smartwatch
13             5       Professional DSLR Camera
14             5       Professional DSLR Camera
15             6                       Smart TV
16             6                       Smart TV
17             7                         Tablet
18             7                         Tablet
19             8                 Gaming Console
20             8                 Gaming Console
21             9  Energy-Efficient Refrigerator

                                          description   price   unit  \
0         High-end smartphone with advanced features.  599.99  Piece
1         High-end smartphone with advanced features.  599.99  Piece
2         High-end smartphone with advanced features.  599.99  Piece
3         High-end smartphone with advanced features.  599.99  Piece
4                Powerful laptop for work and gaming.  999.99  Piece
5                Powerful laptop for work and gaming.  999.99  Piece
6                Powerful laptop for work and gaming.  999.99  Piece
7                Powerful laptop for work and gaming.  999.99  Piece
8   Premium wireless headphones with noise-cancell...  149.99  Piece
9   Premium wireless headphones with noise-cancell...  149.99  Piece
10  Premium wireless headphones with noise-cancell...  149.99  Piece
11   Feature-packed smartwatch with fitness tracking.  199.99  Piece
12   Feature-packed smartwatch with fitness tracking.  199.99  Piece
13  High-quality DSLR camera for photography enthu...  499.99  Piece
14  High-quality DSLR camera for photography enthu...  499.99  Piece
15  High-definition smart TV with built-in streami...  799.99  Piece
16  High-definition smart TV with built-in streami...  799.99  Piece
17  Compact tablet for productivity and entertainm...  299.99  Piece
18  Compact tablet for productivity and entertainm...  299.99  Piece
19  Next-gen gaming console for immersive gaming e...  399.99  Piece
20  Next-gen gaming console for immersive gaming e...  399.99  Piece
21   Modern refrigerator with energy-saving features.  599.99  Piece

                                          image  discount  availability  \
0     https://example.com/images/smartphone.jpg        10          True
1     https://example.com/images/smartphone.jpg        10          True
2     https://example.com/images/smartphone.jpg        10          True
3     https://example.com/images/smartphone.jpg        10          True
4         https://example.com/images/laptop.jpg         5          True
5         https://example.com/images/laptop.jpg         5          True
6         https://example.com/images/laptop.jpg         5          True
7         https://example.com/images/laptop.jpg         5          True
8     https://example.com/images/headphones.jpg        15          True
9     https://example.com/images/headphones.jpg        15          True
10    https://example.com/images/headphones.jpg        15          True
11    https://example.com/images/smartwatch.jpg        10          True
12    https://example.com/images/smartwatch.jpg        10          True
13        https://example.com/images/camera.jpg         5          True
14        https://example.com/images/camera.jpg         5          True
15            https://example.com/images/tv.jpg         8          True
16            https://example.com/images/tv.jpg         8          True
17        https://example.com/images/tablet.jpg        12          True
18        https://example.com/images/tablet.jpg        12          True
19       https://example.com/images/console.jpg        10          True
20       https://example.com/images/console.jpg        10          True
21  https://example.com/images/refrigerator.jpg         5          True

           brand     category  rating  rating.1  \
0         BrandX  Electronics     4.5       5.0
1         BrandX  Electronics     4.5       5.0
2         BrandX  Electronics     4.5       4.0
3         BrandX  Electronics     4.5       4.0
4         BrandY  Electronics     4.7       5.0
5         BrandY  Electronics     4.7       5.0
6         BrandY  Electronics     4.7       4.0
7         BrandY  Electronics     4.7       4.0
8   SoundMasters  Electronics     4.8       5.0
9   SoundMasters  Electronics     4.8       5.0
10  SoundMasters  Electronics     4.8       4.0
11      TechWear    Wearables     4.6       4.0
12      TechWear    Wearables     4.6       5.0
13      PhotoPro      Cameras     4.9       5.0
14      PhotoPro      Cameras     4.9       4.0
15      ViewTech  Electronics     4.7       5.0
16      ViewTech  Electronics     4.7       4.0
17       TabTech  Electronics     4.4       4.0
18       TabTech  Electronics     4.4       5.0
19         GameX       Gaming     4.8       5.0
20         GameX       Gaming     4.8       4.0
21      CoolTech   Appliances     4.6       NaN

                                              comment      _merge
0                   Great phone with a superb camera!        both
1                   Great phone with a superb camera!        both
2   Good performance, but the battery life could b...        both
3   Good performance, but the battery life could b...        both
4         Excellent laptop for gaming and work tasks.        both
5         Excellent laptop for gaming and work tasks.        both
6                           Good value for the price.        both
7                           Good value for the price.        both
8                Top-notch sound quality and comfort.        both
9                Top-notch sound quality and comfort.        both
10   Impressive noise-cancellation, but a bit pricey.  right_only
11            Great value for the features it offers.  right_only
12        Sleek design and accurate fitness tracking.  right_only
13         Exceptional image quality and versatility.  right_only
14         A bit heavy, but the results are worth it.  right_only
15  Stunning picture quality and user-friendly int...  right_only
16  A great addition to our home entertainment setup.  right_only
17  Good value for the price, but the battery life...  right_only
18   Ideal for both work and entertainment on the go.  right_only
19        Incredible gaming performance and graphics.  right_only
20                A must-have for gaming enthusiasts.  right_only
21                                                NaN  right_only