### Find all the products which has no orders
### Join Users with Orders
### Find all the users who have never placed an order
### Find top 5 products with orders

In [1]:
import requests
import pandas as pd
import sqlite3
from IPython.display import display

In [36]:
# Fetching API's
users = requests.get("https://fakestoreapi.com/users/").json()
products = requests.get("https://fakestoreapi.com/products/").json()
carts = requests.get("https://fakestoreapi.com/carts").json()

## convert **users** row data into structured dataframe

In [4]:
# Convert to dataframe
df = pd.DataFrame(users)

# Drop irrelevant columns
df.columns

df.drop(columns=['address','__v'], inplace=True)
df.head()

,id,email,username,password,name,phone
0,1,john@gmail.com,johnd,m38rmF$,"{'firstname': 'john', 'lastname': 'doe'}",1-570-236-7033
1,2,morrison@gmail.com,mor_2314,83r5^_,"{'firstname': 'david', 'lastname': 'morrison'}",1-570-236-7033
2,3,kevin@gmail.com,kevinryan,kev02937@,"{'firstname': 'kevin', 'lastname': 'ryan'}",1-567-094-1345
3,4,don@gmail.com,donero,ewedon,"{'firstname': 'don', 'lastname': 'romer'}",1-765-789-6734
4,5,derek@gmail.com,derek,jklg*_56,"{'firstname': 'derek', 'lastname': 'powell'}",1-956-001-1945

In [5]:
df['firstname'] = df['name'].apply(lambda x: x['firstname'])
df['lastname'] = df['name'].apply(lambda x: x['lastname'])

# Drop the original 'name' column
df.drop(columns=['name'], inplace=True)

# Assign the processed DataFrame to users_data
users_data = df.copy()

# Display the first few rows of the updated users_data DataFrame
print(users_data.head())
users_data.to_csv('users_data.csv', index=False)

   id               email   username   password           phone firstname  \
0   1      john@gmail.com      johnd    m38rmF$  1-570-236-7033      john
1   2  morrison@gmail.com   mor_2314     83r5^_  1-570-236-7033     david
2   3     kevin@gmail.com  kevinryan  kev02937@  1-567-094-1345     kevin
3   4       don@gmail.com     donero     ewedon  1-765-789-6734       don
4   5     derek@gmail.com      derek   jklg*_56  1-956-001-1945     derek

   lastname
0       doe
1  morrison
2      ryan
3     romer
4    powell

## convert **product** row data into structured dataframe

In [11]:
# Convert to dataframe
df = pd.DataFrame(products)
df.columns

Index(['id', 'title', 'price', 'description', 'category', 'image', 'rating'], dtype='object')

In [12]:
df.head()

,id,title,price,description,category,image,rating
0,1,"Fjallraven - Foldsack No. 1 Backpack, Fits 15 ...",109.95,Your perfect pack for everyday use and walks i...,men's clothing,https://fakestoreapi.com/img/81fPKd-2AYL._AC_S...,"{'rate': 3.9, 'count': 120}"
1,2,Mens Casual Premium Slim Fit T-Shirts,22.30,"Slim-fitting style, contrast raglan long sleev...",men's clothing,https://fakestoreapi.com/img/71-3HjGNDUL._AC_S...,"{'rate': 4.1, 'count': 259}"
2,3,Mens Cotton Jacket,55.99,great outerwear jackets for Spring/Autumn/Wint...,men's clothing,https://fakestoreapi.com/img/71li-ujtlUL._AC_U...,"{'rate': 4.7, 'count': 500}"
3,4,Mens Casual Slim Fit,15.99,The color could be slightly different between ...,men's clothing,https://fakestoreapi.com/img/71YXzeOuslL._AC_U...,"{'rate': 2.1, 'count': 430}"
4,5,John Hardy Women's Legends Naga Gold & Silver ...,695.00,"From our Legends Collection, the Naga was insp...",jewelery,https://fakestoreapi.com/img/71pWzhdJNwL._AC_U...,"{'rate': 4.6, 'count': 400}"

In [13]:
# Drop irrelevant columns
df.drop(columns=['description', 'image'], inplace=True)
df.head()

,id,title,price,category,rating
0,1,"Fjallraven - Foldsack No. 1 Backpack, Fits 15 ...",109.95,men's clothing,"{'rate': 3.9, 'count': 120}"
1,2,Mens Casual Premium Slim Fit T-Shirts,22.30,men's clothing,"{'rate': 4.1, 'count': 259}"
2,3,Mens Cotton Jacket,55.99,men's clothing,"{'rate': 4.7, 'count': 500}"
3,4,Mens Casual Slim Fit,15.99,men's clothing,"{'rate': 2.1, 'count': 430}"
4,5,John Hardy Women's Legends Naga Gold & Silver ...,695.00,jewelery,"{'rate': 4.6, 'count': 400}"

In [14]:
df['rate'] = df['rating'].apply(lambda x: x['rate'])
df['count'] = df['rating'].apply(lambda x: x['count'])

# Drop the original 'rating' column
df.drop(columns=['rating'], inplace=True)

In [15]:
df.head()

,id,title,price,category,rate,count
0,1,"Fjallraven - Foldsack No. 1 Backpack, Fits 15 ...",109.95,men's clothing,3.9,120
1,2,Mens Casual Premium Slim Fit T-Shirts,22.30,men's clothing,4.1,259
2,3,Mens Cotton Jacket,55.99,men's clothing,4.7,500
3,4,Mens Casual Slim Fit,15.99,men's clothing,2.1,430
4,5,John Hardy Women's Legends Naga Gold & Silver ...,695.00,jewelery,4.6,400

In [16]:
df.to_csv('products_data.csv', index=False)

## convert **carts** row data into structured dataframe

In [17]:
df = pd.DataFrame(carts)
df.columns

Index(['id', 'userId', 'date', 'products', '__v'], dtype='object')

In [18]:
# Drop irrelevant columns
df.drop(columns='__v', inplace=True)
df.head()

,id,userId,date,products
0,1,1,2020-03-02T00:00:00.000Z,"[{'productId': 1, 'quantity': 4}, {'productId'..."
1,2,1,2020-01-02T00:00:00.000Z,"[{'productId': 2, 'quantity': 4}, {'productId'..."
2,3,2,2020-03-01T00:00:00.000Z,"[{'productId': 1, 'quantity': 2}, {'productId'..."
3,4,3,2020-01-01T00:00:00.000Z,"[{'productId': 1, 'quantity': 4}]"
4,5,3,2020-03-01T00:00:00.000Z,"[{'productId': 7, 'quantity': 1}, {'productId'..."

In [21]:
# convert date column datatype from object to datetime
df['date'] = df['date'].apply(lambda x: x.split('T')[0])
df['date'] = pd.to_datetime(df['date'])
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 7 entries, 0 to 6
Data columns (total 4 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   id        7 non-null      int64
 1   userId    7 non-null      int64
 2   date      7 non-null      datetime64[ns]
 3   products  7 non-null      object
dtypes: datetime64[ns](1), int64(2), object(1)
memory usage: 356.0+ bytes

In [25]:
df['product_id'] = df['products'].apply(lambda x: [item['productId'] for item in x])
df['quantity'] = df['products'].apply(lambda x: [item['quantity'] for item in x])

In [26]:
# Drop the original 'products' column
df.drop(columns=['products'], inplace=True)

In [27]:
df.head()

   id  userId       date product_id    quantity
0   1       1 2020-03-02  [1, 2, 3]   [4, 1, 6]
1   2       1 2020-01-02  [2, 1, 5]  [4, 10, 2]
2   3       2 2020-03-01     [1, 9]      [2, 1]
3   4       3 2020-01-01        [1]         [4]
4   5       3 2020-03-01     [7, 8]      [1, 1]

In [37]:
df_carts_flat = df.explode(['product_id', 'quantity'])

df_carts_flat.rename(columns={'id': 'cart_id', 'product_id': 'product_id_in_cart'}, inplace=True)

# Convert product_id and quantity to numeric types
df_carts_flat['product_id_in_cart'] = pd.to_numeric(df_carts_flat['product_id_in_cart'])
df_carts_flat['quantity'] = pd.to_numeric(df_carts_flat['quantity'])

df_carts_flat.to_csv('carts_data.csv', index=False)

display(df_carts_flat.head())

   cart_id  userId       date  product_id_in_cart  quantity
0        1       1 2020-03-02                   1         4
0        1       1 2020-03-02                   2         1
0        1       1 2020-03-02                   3         6
1        2       1 2020-01-02                   2         4
1        2       1 2020-01-02                   1        10

------------------------------------------------------------------
 ### **Loading All the Cleaning Dataset**
-----------------------------------------------------------------

In [38]:
users = pd.read_csv('users_data.csv')
products = pd.read_csv('products_data.csv')
carts = pd.read_csv('carts_data.csv')

------------------------------------------------------------------
 ### **Create an In-Memory SQLite Database**
-----------------------------------------------------------------

In [39]:
conn = sqlite3.connect(":memory:")

print("SQLite in-memory database created")

SQLite in-memory database created

------------------------------------------------------------------
 ### **Load Pandas DataFrames into SQLite Tables**
-----------------------------------------------------------------

In [41]:
users.to_sql("users", conn, if_exists="replace", index=False)
products.to_sql("products", conn, if_exists="replace", index=False)
carts.to_sql("carts", conn, if_exists="replace", index=False)

print("Tables loaded into SQLite")

Tables loaded into SQLite

------------------------------------------------------------------
 ### **Task 01 : Find all the users who have never placed an order**
-----------------------------------------------------------------

In [42]:
users_no_orders = pd.read_sql_query(
    """
      SELECT
          u.id,
          u.email,
          u.username,
          u.firstname,
          u.lastname
      FROM users u
      LEFT JOIN carts c ON u.id = c.userId
      WHERE c.userId IS NULL
      """, conn)
print("Users who have never placed an order:")
display(users_no_orders)

Users who have never placed an order:

   id              email  username firstname lastname
0   5    derek@gmail.com     derek     derek   powell
1   6  david_r@gmail.com   david_r     david  russell
2   7   miriam@gmail.com    snyder    miriam   snyder
3   9     kate@gmail.com    kate_h      kate     hale
4  10   jimmie@gmail.com  jimmie_k    jimmie    klein

------------------------------------------------------------------
 ### **Task 02 : Find all the products which has no orders**
-----------------------------------------------------------------

In [44]:
query_products_no_orders = """
SELECT
    p.id,
    p.title,
    p.price,
    p.category,
    p.rate,
    p.count
FROM products p
LEFT JOIN carts c ON p.id = c.product_id_in_cart
WHERE c.product_id_in_cart IS NULL
"""

products_no_orders_sql = pd.read_sql_query(query_products_no_orders, conn)
print("Products with no orders:")
display(products_no_orders_sql)

Products with no orders:

,id,title,price,category,rate,count
0,4,Mens Casual Slim Fit,15.99,men's clothing,2.1,430
1,6,Solid Gold Petite Micropave,168.00,jewelery,3.9,70
2,11,Silicon Power 256GB SSD 3D NAND A55 SLC Cache ...,109.00,electronics,4.8,319
3,13,Acer SB220Q bi 21.5 inches Full HD (1920 x 108...,599.00,electronics,2.9,250
4,14,Samsung 49-Inch CHG90 144Hz Curved Gaming Moni...,999.99,electronics,2.2,140
5,15,BIYLACLESEN Women's 3-in-1 Snowboard Jacket Wi...,56.99,women's clothing,2.6,235
6,16,Lock and Love Women's Removable Hooded Faux Le...,29.95,women's clothing,2.9,340
7,17,Rain Jacket Women Windbreaker Striped Climbing...,39.99,women's clothing,3.8,679
8,19,Opna Women's Short Sleeve Moisture,7.95,women's clothing,4.5,146
9,20,DANVOUY Womens T Shirt Casual Cotton Short,12.99,women's clothing,3.6,145

------------------------------------------------------------------
### **Task 03: Find top 5 products with orders**
------------------------------------------------------------------

In [45]:
query_top_5_products = """
SELECT
    p.id AS product_id,
    p.title,
    p.category,
    SUM(c.quantity) AS total_quantity_ordered
FROM products p
JOIN carts c ON p.id = c.product_id_in_cart
GROUP BY p.id, p.title, p.category
ORDER BY total_quantity_ordered DESC
LIMIT 5
"""

top_5_products = pd.read_sql_query(query_top_5_products, conn)
print("Top 5 products with orders:")
display(top_5_products)

Top 5 products with orders:

,product_id,title,category,total_quantity_ordered
0,1,"Fjallraven - Foldsack No. 1 Backpack, Fits 15 ...",men's clothing,20
1,3,Mens Cotton Jacket,men's clothing,6
2,2,Mens Casual Premium Slim Fit T-Shirts,men's clothing,5
3,12,WD 4TB Gaming Drive Works with Playstation 4 P...,electronics,3
4,5,John Hardy Women's Legends Naga Gold & Silver ...,jewelery,2

------------------------------------------------------------------
### **Task 04: Join Users with Orders**
------------------------------------------------------------------

In [47]:
query_users_with_orders = """
SELECT
    u.id AS user_id,
    u.firstname,
    u.lastname,
    u.email,
    c.cart_id,
    c.date AS order_date,
    c.product_id_in_cart,
    c.quantity
FROM users u
JOIN carts c ON u.id = c.userId
ORDER BY u.id, c.date
"""

users_with_orders = pd.read_sql_query(query_users_with_orders, conn)
print("Users joined with their orders:")
display(users_with_orders.head(10))

Users joined with their orders:

,user_id,firstname,lastname,email,cart_id,order_date,product_id_in_cart,quantity
0,1,john,doe,john@gmail.com,2,2020-01-02,1,10
1,1,john,doe,john@gmail.com,2,2020-01-02,2,4
2,1,john,doe,john@gmail.com,2,2020-01-02,5,2
3,1,john,doe,john@gmail.com,1,2020-03-02,1,4
4,1,john,doe,john@gmail.com,1,2020-03-02,2,1
5,1,john,doe,john@gmail.com,1,2020-03-02,3,6
6,2,david,morrison,morrison@gmail.com,3,2020-03-01,1,2
7,2,david,morrison,morrison@gmail.com,3,2020-03-01,9,1
8,3,kevin,ryan,kevin@gmail.com,4,2020-01-01,1,4
9,3,kevin,ryan,kevin@gmail.com,5,2020-03-01,7,1