In [7]:
import requests
import pandas as pd

In [2]:
product = requests.get('https://fake-store-api.mock.beeceptor.com/api/products').json()

In [5]:
product_id, name, description, price, unit, image, discount, availability, brand, category, rating = [], [], [], [], [], [], [], [], [], [], []

In [6]:
for p in product:
  product_id.append(p['product_id'])
  name.append(p['name'])
  description.append(p['description'])
  price.append(p['price'])
  unit.append(p['unit'])
  image.append(p['image'])
  discount.append(p['discount'])
  availability.append(p['availability'])
  brand.append(p['brand'])
  category.append(p['category'])
  rating.append(p['rating'])

In [8]:
data = pd.DataFrame({
    'product_id': product_id,
    'name': name,
    'description': description,
    'price': price,
    'unit': unit,
    'image': image,
    'discount': discount,
    'availability': availability,
    'brand': brand,
    'category': category,
    'rating': rating
})

In [9]:
print(data)

   product_id                           name  \
0           1                     Smartphone
1           2                         Laptop
2           3            Wireless Headphones
3           4                     Smartwatch
4           5       Professional DSLR Camera
5           6                       Smart TV
6           7                         Tablet
7           8                 Gaming Console
8           9  Energy-Efficient Refrigerator

                                         description   price   unit  \
0        High-end smartphone with advanced features.  599.99  Piece
1               Powerful laptop for work and gaming.  999.99  Piece
2  Premium wireless headphones with noise-cancell...  149.99  Piece
3   Feature-packed smartwatch with fitness tracking.  199.99  Piece
4  High-quality DSLR camera for photography enthu...  499.99  Piece
5  High-definition smart TV with built-in streami...  799.99  Piece
6  Compact tablet for productivity and entertainm...  299.99  Piece
7  Next-gen gaming console for immersive gaming e...  399.99  Piece
8   Modern refrigerator with energy-saving features.  599.99  Piece

                                         image  discount  availability  \
0    https://example.com/images/smartphone.jpg        10          True
1        https://example.com/images/laptop.jpg         5          True
2    https://example.com/images/headphones.jpg        15          True
3    https://example.com/images/smartwatch.jpg        10          True
4        https://example.com/images/camera.jpg         5          True
5            https://example.com/images/tv.jpg         8          True
6        https://example.com/images/tablet.jpg        12          True
7       https://example.com/images/console.jpg        10          True
8  https://example.com/images/refrigerator.jpg         5          True

          brand     category  rating
0        BrandX  Electronics     4.5
1        BrandY  Electronics     4.7
2  SoundMasters  Electronics     4.8
3      TechWear    Wearables     4.6
4      PhotoPro      Cameras     4.9
5      ViewTech  Electronics     4.7
6       TabTech  Electronics     4.4
7         GameX       Gaming     4.8
8      CoolTech   Appliances     4.6

In [12]:
data.to_csv('product.csv', index=False)
data.to_excel('product.xlsx', index=False)
data.to_json('product.json', orient='records', indent=4)
data.to_parquet('product.parquet', index=False)

In [25]:
df = pd.read_csv('product.csv')
df.head()

,product_id,name,description,price,unit,image,discount,availability,brand,category,rating
0,1,Smartphone,High-end smartphone with advanced features.,599.99,Piece,https://example.com/images/smartphone.jpg,10,True,BrandX,Electronics,4.5
1,2,Laptop,Powerful laptop for work and gaming.,999.99,Piece,https://example.com/images/laptop.jpg,5,True,BrandY,Electronics,4.7
2,3,Wireless Headphones,Premium wireless headphones with noise-cancell...,149.99,Piece,https://example.com/images/headphones.jpg,15,True,SoundMasters,Electronics,4.8
3,4,Smartwatch,Feature-packed smartwatch with fitness tracking.,199.99,Piece,https://example.com/images/smartwatch.jpg,10,True,TechWear,Wearables,4.6
4,5,Professional DSLR Camera,High-quality DSLR camera for photography enthu...,499.99,Piece,https://example.com/images/camera.jpg,5,True,PhotoPro,Cameras,4.9

In [26]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 9 entries, 0 to 8
Data columns (total 11 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   product_id    9 non-null      int64
 1   name          9 non-null      object
 2   description   9 non-null      object
 3   price         9 non-null      float64
 4   unit          9 non-null      object
 5   image         9 non-null      object
 6   discount      9 non-null      int64
 7   availability  9 non-null      bool
 8   brand         9 non-null      object
 9   category      9 non-null      object
 10  rating        9 non-null      float64
dtypes: bool(1), float64(2), int64(2), object(6)
memory usage: 861.0+ bytes

In [27]:
df.describe()

       product_id       price   discount    rating
count    9.000000    9.000000   9.000000  9.000000
mean     5.000000  505.545556   8.888889  4.666667
std      2.738613  278.886676   3.480102  0.158114
min      1.000000  149.990000   5.000000  4.400000
25%      3.000000  299.990000   5.000000  4.600000
50%      5.000000  499.990000  10.000000  4.700000
75%      7.000000  599.990000  10.000000  4.800000
max      9.000000  999.990000  15.000000  4.900000

In [28]:
df.columns

Index(['product_id', 'name', 'description', 'price', 'unit', 'image',
       'discount', 'availability', 'brand', 'category', 'rating'],
      dtype='object')

In [29]:
df.tail()

,product_id,name,description,price,unit,image,discount,availability,brand,category,rating
4,5,Professional DSLR Camera,High-quality DSLR camera for photography enthu...,499.99,Piece,https://example.com/images/camera.jpg,5,True,PhotoPro,Cameras,4.9
5,6,Smart TV,High-definition smart TV with built-in streami...,799.99,Piece,https://example.com/images/tv.jpg,8,True,ViewTech,Electronics,4.7
6,7,Tablet,Compact tablet for productivity and entertainm...,299.99,Piece,https://example.com/images/tablet.jpg,12,True,TabTech,Electronics,4.4
7,8,Gaming Console,Next-gen gaming console for immersive gaming e...,399.99,Piece,https://example.com/images/console.jpg,10,True,GameX,Gaming,4.8
8,9,Energy-Efficient Refrigerator,Modern refrigerator with energy-saving features.,599.99,Piece,https://example.com/images/refrigerator.jpg,5,True,CoolTech,Appliances,4.6

In [30]:
df['category'].value_counts()

category
Electronics    5
Wearables      1
Cameras        1
Gaming         1
Appliances     1
Name: count, dtype: int64

In [33]:
df.iloc[2]

product_id                                                      3
name                                          Wireless Headphones
description     Premium wireless headphones with noise-cancell...
price                                                      149.99
unit                                                        Piece
image                   https://example.com/images/headphones.jpg
discount                                                       15
availability                                                 True
brand                                                SoundMasters
category                                              Electronics
rating                                                        4.8
Name: 2, dtype: object

In [35]:
df.loc[5]

product_id                                                      6
name                                                     Smart TV
description     High-definition smart TV with built-in streami...
price                                                      799.99
unit                                                        Piece
image                           https://example.com/images/tv.jpg
discount                                                        8
availability                                                 True
brand                                                    ViewTech
category                                              Electronics
rating                                                        4.7
Name: 5, dtype: object